type LangMap = { en: string; ms: string; tur: string; urd: string; ben: string; fas: string; zh: string; yue: string; ja: string; ru: string; es: string; ko: string; ta?: string; si?: string };
export type GhuslContentKey = keyof typeof GHUSL_CONTENT;

export const GHUSL_CONTENT = {
  page_title: { en: 'Ghusl: Full-Body Purification', ms: 'Mandi Wajib: Taharah Penuh', tur: 'Gusül: Tam Vücut Temizliği', urd: 'غسل: مکمل جسمانی طہارت', ben: 'গোসল: পূর্ণ শারীরিক পবিত্রতা', fas: 'غسل: طهارت کامل بدن', zh: '大净：全身洁净', yue: '大淨：全身潔淨', ja: 'グスル：全身の清め', ru: 'Гусль: полное омовение тела', es: 'Ghusl: Purificación Corporal Completa', ko: '구슬: 전신 정화' },
  page_subtitle: { en: 'The major ritual purification that lifts the state of janabah and restores full eligibility for worship', ms: 'Taharah besar yang menghilangkan hadas besar dan memulihkan kelayakan penuh untuk beribadah', tur: 'Cünüplük halini gideren ve ibadete tam ehliyeti yenileyen boy abdest', urd: 'بڑی طہارت جو جنابت کی حالت کو دور کرتی ہے اور عبادت کی مکمل اہلیت بحال کرتی ہے', ben: 'বড় পবিত্রতা যা জানাবাতের অবস্থা দূর করে এবং ইবাদতের পূর্ণ যোগ্যতা পুনরুদ্ধার করে', fas: 'طهارت کبری که حالت جنابت را برطرف می‌کند و صلاحیت کامل عبادت را بازمی‌گرداند', zh: '解除大不洁净状态并恢复完全礼拜资格的沐浴净礼', yue: '解除大不潔淨狀態並恢復完全禮拜資格的沐浴淨禮', ja: '大不浄の状態を解消し礼拝の完全な資格を回復する大浄礼', ru: 'Большое ритуальное омовение, снимающее состояние джунуба и восстанавливающее полную пригодность для поклонения', es: 'La purificación ritual mayor que elimina el estado de janabah y restaura la plena aptitud para el culto', ko: '자나바 상태를 해소하고 예배에 완전한 자격을 회복하는 큰 정결 의식' },

  section_whatIs: { en: 'What Is Ghusl?', ms: 'Apakah Mandi Wajib?', tur: 'Gusül Nedir?', urd: 'غسل کیا ہے؟', ben: 'গোসল কী?', fas: 'غسل چیست؟', zh: '什么是大净？', yue: '乜嘢係大淨？', ja: 'グスルとは何ですか？', ru: 'Что такое Гусль?', es: '¿Qué es el Ghusl?', ko: '구슬이란 무엇인가?' },
  section_obligatory: { en: 'What Makes Ghusl Obligatory', ms: 'Perkara yang Mewajibkan Mandi Wajib', tur: 'Gusülü Gerektiren Durumlar', urd: 'غسل کو واجب کرنے والے اسباب', ben: 'যা গোসল ওয়াজিব করে', fas: 'موجبات غسل', zh: '使大净成为义务的情况', yue: '使大淨成為義務的情況', ja: 'グスルが義務となる場合', ru: 'Что делает Гусль обязательным', es: 'Lo que hace obligatorio el Ghusl', ko: '구슬을 의무로 만드는 것' },
  section_method: { en: 'The Method of Ghusl', ms: 'Cara Mandi Wajib', tur: 'Gusül Nasıl Yapılır', urd: 'غسل کا طریقہ', ben: 'গোসলের পদ্ধতি', fas: 'روش غسل', zh: '大净的方法', yue: '大淨的方法', ja: 'グスルの方法', ru: 'Метод Гусля', es: 'El Método del Ghusl', ko: '구슬의 방법' },
  section_permits: { en: 'What Ghusl Permits', ms: 'Apa yang Dibolehkan Selepas Mandi Wajib', tur: 'Gusülün Mübah Kıldıkları', urd: 'غسل کے بعد کیا جائز ہے', ben: 'গোসলের পর কী বৈধ', fas: 'آنچه غسل مباح می‌کند', zh: '大净后允许的事', yue: '大淨後允許的事', ja: 'グスル後に許可されること', ru: 'Что разрешает Гусль', es: 'Lo que permite el Ghusl', ko: '구슬이 허용하는 것' },
  section_spiritual: { en: 'Spiritual Significance', ms: 'Kepentingan Rohani', tur: 'Manevi Önemi', urd: 'روحانی اہمیت', ben: 'আধ্যাত্মিক গুরুত্ব', fas: 'اهمیت معنوی', zh: '精神意义', yue: '精神意義', ja: '精神的な意味', ru: 'Духовное значение', es: 'Significado Espiritual', ko: '정신적 의미' },

  label_transliteration: { en: 'Transliteration', ms: 'Transliterasi', tur: 'Okunuş', urd: 'تلفظ', ben: 'উচ্চারণ', fas: 'نویسه‌گردانی', zh: '转写', yue: '轉寫', ja: '音写', ru: 'Транслитерация', es: 'Transliteración', ko: '로마자 표기' },
  label_minimum: { en: 'The minimum valid ghusl (fard elements):', ms: 'Mandi wajib minimum yang sah (rukun):', tur: 'Asgari geçerli gusül (farz unsurlar):', urd: 'کم از کم درست غسل (فرضی ارکان):', ben: 'সর্বনিম্ন বৈধ গোসল (ফরজ উপাদান):', fas: 'حداقل غسل معتبر (ارکان فرضی):', zh: '最低有效大净（必须要素）：', yue: '最低有效大淨（必須要素）：', ja: '最低限の有効なグスル（義務要素）：', ru: 'Минимальный действительный Гусль (фард-элементы):', es: 'El Ghusl mínimo válido (elementos fard):', ko: '최소 유효한 구슬 (파르드 요소):' },
  label_intro_quran: { en: '"And if you are in a state of janabah, then purify yourselves [by bathing your whole body]." (Al-Maʾidah 5:6)', ms: '"Dan jika kamu berjunub maka mandilah." (Al-Maidah 5:6)', tur: '"Eğer cünüp iseniz, iyice yıkanarak temizlenin." (el-Mâide 5:6)', urd: '"اور اگر تم جنابت کی حالت میں ہو تو پاک ہو جاؤ۔" (المائدہ ۵:۶)', ben: '"যদি তোমরা অপবিত্র হও তাহলে পবিত্র হও।" (আল-মায়িদাহ ৫:৬)', fas: '"و اگر جنب بودید پس پاکیزه شوید." (المائده ۵:۶)', zh: '"如果你们处于大不洁净状态，就要洗涤沐浴。"（马伊达章5:6）', yue: '"如果你哋處於大不潔淨狀態，就要洗滌沐浴。"（馬伊達章5:6）', ja: '"もし大不浄の状態にあるならば、身を清めなさい。"（マーイダ章5:6）', ru: '"Если вы находитесь в состоянии джунуба, то очиститесь [искупайтесь]." (Аль-Маида 5:6)', es: '"Y si estáis en estado de janabah, purificaos [bañando todo el cuerpo]." (Al-Maʾida 5:6)', ko: '"만약 여러분이 자나바 상태에 있다면 몸을 깨끗이 하십시오." (알마이다 5:6)' },

  cause_1_title: { en: 'Janabah  –  Sexual Intercourse', ms: 'Janabah  –  Persetubuhan', tur: 'Cünüplük  –  Cinsel İlişki', urd: 'جنابت  –  مجامعت', ben: 'জানাবাহ  –  যৌন সংসর্গ', fas: 'جنابت  –  نزدیکی', zh: '大不洁净  –  性交', yue: '大不潔淨  –  性交', ja: 'ジュナーバ  –  性交', ru: 'Джунуб  –  Половое сношение', es: 'Janabah  –  Relaciones Sexuales', ko: '자나바  –  성교' },
  cause_2_title: { en: 'Ejaculation (Inzal)', ms: 'Pancutan Air Mani (Inzal)', tur: 'Meni Gelmesi (İnzal)', urd: 'انزال (منی)', ben: 'বীর্যপাত (ইনযাল)', fas: 'انزال (خروج منی)', zh: '射精（因扎勒）', yue: '射精（因扎勒）', ja: '射精（インザール）', ru: 'Семяизвержение (Инзаль)', es: 'Eyaculación (Inzal)', ko: '사정 (인잘)' },
  cause_3_title: { en: 'End of Menstruation (Hayd)', ms: 'Tamat Haid', tur: 'Adet Bitimi (Hayz)', urd: 'حیض کا ختم ہونا', ben: 'মাসিক শেষ হওয়া (হায়ড)', fas: 'پایان حیض', zh: '月经结束（海兹）', yue: '月經結束（海茲）', ja: '月経の終わり（ハイド）', ru: 'Окончание менструации (Хайд)', es: 'Fin de la Menstruación (Hayd)', ko: '생리 종료 (하이드)' },
  cause_4_title: { en: 'Postnatal Bleeding (Nifas)', ms: 'Nifas (Darah Selepas Bersalin)', tur: 'Lohusalık Kanaması (Nifas)', urd: 'نفاس (زچگی کا خون)', ben: 'প্রসব-পরবর্তী রক্তক্ষরণ (নিফাস)', fas: 'خونریزی پس از زایمان (نفاس)', zh: '产后出血（尼法斯）', yue: '產後出血（尼法斯）', ja: '産後出血（ニファース）', ru: 'Послеродовое кровотечение (Нифас)', es: 'Sangrado Posparto (Nifas)', ko: '산후 출혈 (니파스)' },
  cause_5_title: { en: 'Embracing Islam', ms: 'Memeluk Islam', tur: "İslam'a Giriş", urd: 'اسلام قبول کرنا', ben: 'ইসলাম গ্রহণ', fas: 'پذیرفتن اسلام', zh: '皈依伊斯兰', yue: '皈依伊斯蘭', ja: 'イスラム入信', ru: 'Принятие Ислама', es: 'Abrazar el Islam', ko: '이슬람 개종' },
  cause_6_title: { en: 'Death', ms: 'Kematian', tur: 'Ölüm', urd: 'موت', ben: 'মৃত্যু', fas: 'مرگ', zh: '死亡', yue: '死亡', ja: '死亡', ru: 'Смерть', es: 'Muerte', ko: '사망' },

  step_1_title: { en: 'Intention (Niyyah)', ms: 'Niat', tur: 'Niyet (Niyyah)', urd: 'نیت', ben: 'নিয়ত', fas: 'نیت', zh: '意图（尼叶）', yue: '意圖（尼葉）', ja: '意図（ニーヤ）', ru: 'Намерение (Ниййя)', es: 'Intención (Niyyah)', ko: '의도 (니야)' },
  step_2_title: { en: 'Bismillah and Washing Hands', ms: 'Bismillah dan Cuci Tangan', tur: 'Besmele ve Elleri Yıkama', urd: 'بسم اللہ اور ہاتھ دھونا', ben: 'বিসমিল্লাহ ও হাত ধোওয়া', fas: 'بسم‌الله و شستن دست‌ها', zh: '念主名并洗手', yue: '念主名並洗手', ja: 'ビスミッラーと手を洗う', ru: 'Бисмилла и мытьё рук', es: 'Bismillah y Lavado de Manos', ko: '비스밀라와 손 씻기' },
  step_3_title: { en: 'Cleanse Private Parts', ms: 'Bersihkan Kemaluan', tur: 'Avret Yerini Temizleme', urd: 'شرمگاہ کی صفائی', ben: 'গোপনাঙ্গ পরিষ্কার করা', fas: 'تطهیر عورتین', zh: '清洁私处', yue: '清潔私處', ja: 'プライベート部位を清める', ru: 'Очищение интимных частей', es: 'Limpiar las Partes Íntimas', ko: '사적 부위 세정' },
  step_4_title: { en: 'Perform Full Wudu', ms: 'Berwudu Penuh', tur: 'Tam Abdest Almak', urd: 'مکمل وضو کرنا', ben: 'পূর্ণ উযু করা', fas: 'وضو کامل', zh: '完整净礼（小净）', yue: '完整淨禮（小淨）', ja: '完全なウドゥーを行う', ru: 'Совершить полное малое омовение (вуду)', es: 'Realizar el Wudu Completo', ko: '완전한 우두 수행' },
  step_5_title: { en: 'Pour Water Over the Entire Body', ms: 'Tuang Air ke Seluruh Badan', tur: 'Tüm Vücuda Su Dökmek', urd: 'پورے جسم پر پانی بہانا', ben: 'সমগ্র শরীরে পানি ঢালা', fas: 'ریختن آب بر سراسر بدن', zh: '将水倒遍全身', yue: '將水倒遍全身', ja: '全身に水を注ぐ', ru: 'Обмывание всего тела водой', es: 'Verter Agua sobre Todo el Cuerpo', ko: '전신에 물 붓기' },
  step_6_title: { en: 'Wash the Feet (if deferred)', ms: 'Basuh Kaki (jika ditangguhkan)', tur: 'Ayakları Yıkamak (ertelendiyse)', urd: 'پاؤں دھونا (اگر موخر کیا ہو)', ben: 'পা ধোওয়া (যদি পিছিয়ে রাখা হয়)', fas: 'شستن پاها (در صورت تعویق)', zh: '洗脚（若已推迟）', yue: '洗腳（若已推遲）', ja: '足を洗う（延期した場合）', ru: 'Мытьё ног (если отложено)', es: 'Lavar los Pies (si se difirió)', ko: '발 씻기 (연기된 경우)' },

  permit_1: { en: 'Performing the five daily prayers', ms: 'Mendirikan solat lima waktu', tur: 'Beş vakit namaz kılmak', urd: 'پانچ وقت کی نماز ادا کرنا', ben: 'পাঁচ ওয়াক্ত নামাজ পড়া', fas: 'گزاردن نمازهای پنجگانه', zh: '进行五次日常礼拜', yue: '進行五次日常禮拜', ja: '五時の礼拝を行う', ru: 'Совершение пятикратной молитвы', es: 'Realizar las cinco oraciones diarias', ko: '다섯 번의 일일 예배 수행' },
  permit_2: { en: 'Reciting or touching the Quran', ms: 'Membaca atau menyentuh al-Quran', tur: "Kur'an okumak veya dokunmak", urd: 'قرآن تلاوت کرنا یا چھونا', ben: 'কুরআন তিলাওয়াত বা স্পর্শ করা', fas: 'تلاوت یا لمس قرآن', zh: '诵读或触摸《古兰经》', yue: '誦讀或觸摸《古蘭經》', ja: 'クルアーンを朗誦または触れる', ru: 'Чтение Корана или прикосновение к нему', es: 'Recitar o tocar el Corán', ko: '쿠란 낭독 또는 접촉' },
  permit_3: { en: 'Entering and remaining in the mosque', ms: 'Memasuki dan berada di masjid', tur: 'Camiye girmek ve kalmak', urd: 'مسجد میں داخل ہونا اور رہنا', ben: 'মসজিদে প্রবেশ ও অবস্থান', fas: 'ورود و توقف در مسجد', zh: '进入并留在清真寺', yue: '進入並留在清真寺', ja: 'モスクへの入場と滞在', ru: 'Вход в мечеть и пребывание в ней', es: 'Entrar y permanecer en la mezquita', ko: '모스크 입장 및 체류' },
  permit_4: { en: "Performing tawaf around the Ka'bah", ms: "Melakukan tawaf di sekeliling Ka'bah", tur: "Kâbe'yi tavaf etmek", urd: 'کعبہ کا طواف کرنا', ben: 'কাবার চারপাশে তাওয়াফ করা', fas: 'طواف به دور کعبه', zh: '绕克尔白进行塔瓦夫', yue: '繞克爾白進行塔瓦夫', ja: 'カーバを巡礼する', ru: 'Совершение таваф вокруг Каабы', es: "Realizar el tawaf alrededor de la Ka'bah", ko: '카바 주위를 도는 타와프' },
  permit_5: { en: 'Observing the obligatory fast', ms: 'Berpuasa wajib', tur: 'Farz oruç tutmak', urd: 'فرض روزہ رکھنا', ben: 'ফরজ রোজা রাখা', fas: 'نگه داشتن روزه واجب', zh: '守斋', yue: '守齋', ja: '義務の断食を守る', ru: 'Соблюдение обязательного поста', es: 'Observar el ayuno obligatorio', ko: '의무 단식 준수' },
  permit_6: { en: 'Marital intimacy (after menstruation or nifas)', ms: 'Hubungan suami isteri (selepas haid atau nifas)', tur: 'Eşler arası yakınlık (hayz veya nifas sonrası)', urd: 'ازدواجی تعلق (حیض یا نفاس کے بعد)', ben: 'দাম্পত্য ঘনিষ্ঠতা (মাসিক বা নিফাসের পরে)', fas: 'صمیمیت زناشویی (پس از حیض یا نفاس)', zh: '夫妻亲密（月经或产后出血后）', yue: '夫妻親密（月經或產後出血後）', ja: '夫婦の親密さ（月経またはニファース後）', ru: 'Супружеская близость (после менструации или нифаса)', es: 'Intimidad conyugal (después de la menstruación o el nifas)', ko: '부부 친밀감 (생리 또는 니파스 후)' },

  closing_verse: { en: '"Indeed, Allah loves those who are constantly repentant and loves those who purify themselves." (Al-Baqarah 2:222)', ms: '"Sesungguhnya Allah menyukai orang-orang yang bertaubat dan menyukai orang-orang yang mensucikan diri." (Al-Baqarah 2:222)', tur: '"Şüphesiz Allah, çok tövbe edenleri ve çok temizlenenleri sever." (Bakara 2:222)', urd: '"بے شک اللہ توبہ کرنے والوں اور پاک رہنے والوں کو دوست رکھتا ہے۔" (البقرہ ۲:۲۲۲)', ben: '"নিশ্চয়ই আল্লাহ তওবাকারীদের ভালোবাসেন এবং পবিত্রতা অর্জনকারীদের ভালোবাসেন।" (আল-বাকারাহ ২:২২২)', fas: '"همانا خداوند توبه‌کاران و پاکیزگان را دوست دارد." (البقره ۲:۲۲۲)', zh: '"真主喜爱不断悔罪的人，喜爱洁净自身的人。"（巴格拉章2:222）', yue: '"真主喜愛不斷悔罪的人，喜愛潔淨自身的人。"（巴格拉章2:222）', ja: '"まことにアッラーは絶えず悔悛する者を愛し、身を清める者を愛し給う。"（バカラ章2:222）', ru: '"Поистине, Аллах любит кающихся и любит очищающихся." (Аль-Бакара 2:222)', es: '"En verdad, Allah ama a quienes constantemente se arrepienten y ama a quienes se purifican." (Al-Baqarah 2:222)', ko: '"진실로 알라는 끊임없이 회개하는 자들과 스스로를 정화하는 자들을 사랑한다." (알바카라 2:222)' },
} satisfies Record<string, LangMap>;
