type LangMap = { en: string; ms: string; tur: string; urd: string; ben: string; fas: string; zh: string; yue: string; ja: string; ru: string; es: string; ko: string; ta: string; si: string };
export type NamesContentKey = keyof typeof NAMES_CONTENT;

export const NAMES_CONTENT = {
  page_title: { en: `The 99 Names of Allah`, ms: `99 Nama Allah`, tur: `Allah'ın 99 İsmi`, urd: `اللہ کے 99 نام`, ben: `আল্লাহর ৯৯টি নাম`, fas: `۹۹ نام الله`, zh: `真主的99个名字`, yue: `真主嘅99個名字`, ja: `アッラーの99の御名`, ru: `99 имён Аллаха`, es: `Los 99 Nombres de Allah`, ko: `알라의 99가지 이름`, ta: `அல்லாஹ்வின் 99 பெயர்கள்`, si: `අල්ලාහ්ගේ නාම 99` },
  page_subtitle: { en: `Allah - Exalted be He - has beautiful names. The Prophet ﷺ said: "Allah has ninety-nine names; whoever memorises them all will enter Paradise." (Bukhari)`, ms: `Allah - Maha Tinggi Dia - mempunyai nama-nama yang indah. Nabi ﷺ bersabda: "Allah mempunyai sembilan puluh sembilan nama; sesiapa yang menghafalnya semua akan masuk Syurga." (Bukhari)`, tur: `Allah - Yüce O - güzel isimler sahibidir. Peygamber ﷺ şöyle buyurdu: "Allah'ın doksan dokuz ismi vardır; onların hepsini ezberleyenler Cennete girecektir." (Buhârî)`, urd: `اللہ - اسے بلند شان حاصل ہے - کے خوبصورت نام ہیں۔ نبی ﷺ نے فرمایا: "اللہ کے ننانوے نام ہیں؛ جو انہیں یاد کر لے وہ جنت میں داخل ہو گا۔" (بخاری)`, ben: `আল্লাহ - মহিমান্বিত তিনি - সুন্দর নামের অধিকারী। নবী ﷺ বলেছেন: "আল্লাহর নিরানব্বইটি নাম আছে; যে সেগুলো সব মুখস্থ করবে সে জান্নাতে প্রবেশ করবে।" (বুখারি)`, fas: `الله - عز و جل - نام‌های زیبا دارد. پیامبر ﷺ فرمودند: «الله نود و نه نام دارد؛ هر که همه آن‌ها را حفظ کند وارد بهشت می‌شود.» (بخاری)`, zh: `真主——赞美他——有美好的名字。先知ﷺ说："真主有九十九个名字；凡背诵这些名字者将进入乐园。"（布哈里）`, yue: `真主——讚美祂——有美好嘅名字。先知ﷺ說："真主有九十九個名字；凡背誦呢啲名字者將進入樂園。"（布哈里）`, ja: `アッラー（賞賛と称賛あれ）には美しいお名前がある。預言者ﷺは仰った：「アッラーには99の御名がある。それを全て暗記した者は楽園に入る。」（ブハーリー）`, ru: `Аллах — Преславный — обладает прекрасными именами. Пророк ﷺ сказал: «У Аллаха девяносто девять имён; тот, кто запомнит их все, войдёт в Рай.» (Бухари)`, es: `Allah — Exaltado sea — tiene hermosos nombres. El Profeta ﷺ dijo: "Allah tiene noventa y nueve nombres; quien los memorice todos entrará en el Paraíso." (Bujari)`, ko: `알라 - 그분께 찬미를 - 는 아름다운 이름을 가지고 계신다. 예언자 ﷺ 가 말씀하셨다: "알라께는 아흔아홉 가지 이름이 있으니, 이를 모두 암기한 자는 낙원에 들어갈 것이다." (부하리)`, ta: `அல்லாஹ் - அவனுக்கு உயர்வு உண்டாகுக - அழகான பெயர்கள் உடையவன். நபி ﷺ கூறினார்கள்: "அல்லாஹ்விற்கு தொண்ணூற்றொன்பது பெயர்கள் உள்ளன; அவை அனைத்தையும் மனப்பாடம் செய்தவர் சொர்க்கத்தில் நுழைவார்." (புகாரி)`, si: `අල්ලාහ් - ඔහු උදාත්ත වේ - ට සුන්දර නාම ඇත. නබිතුමා ﷺ වදාළ සේක: "අල්ලාහ්ට නව-අනූ නාම ඇත; ඒ සියල්ල කටපාඩම් කළ තැනැත්තා ස්වර්ගයට ඇතුළු වන්නේය." (බුහාරි)` },
  search_placeholder: { en: `Search by name, meaning, or transliteration…`, ms: `Cari mengikut nama, makna, atau transliterasi…`, tur: `İsim, anlam veya transkripsiyon ile arayın…`, urd: `نام، معنی، یا تحریف کے ذریعے تلاش کریں…`, ben: `নাম, অর্থ বা প্রতিবর্ণীকরণ দিয়ে খুঁজুন…`, fas: `بر اساس نام، معنا، یا آوانویسی جستجو کنید…`, zh: `按名字、含义或音译搜索…`, yue: `按名字、含義或音譯搜索…`, ja: `名前・意味・発音表記で検索…`, ru: `Поиск по имени, значению или транслитерации…`, es: `Buscar por nombre, significado o transliteración…`, ko: `이름, 의미, 음역으로 검색…`, ta: `பெயர், பொருள் அல்லது ஒலிப்பு மூலம் தேடுங்கள்…`, si: `නම, තේරුම, හෝ ලිපිලේඛනය මගින් සොයන්න…` },
  search_aria: { en: `Search the 99 names`, ms: `Cari 99 nama`, tur: `99 ismi ara`, urd: `99 نام تلاش کریں`, ben: `৯৯ নাম অনুসন্ধান করুন`, fas: `۹۹ نام را جستجو کنید`, zh: `搜索99个名字`, yue: `搜索99個名字`, ja: `99の御名を検索する`, ru: `Поиск 99 имён`, es: `Buscar los 99 nombres`, ko: `99가지 이름 검색`, ta: `99 பெயர்களை தேடுங்கள்`, si: `නාම 99 සොයන්න` },
  no_results: { en: `No names match your search.`, ms: `Tiada nama yang sepadan dengan carian anda.`, tur: `Aramanızla eşleşen isim bulunamadı.`, urd: `آپ کی تلاش سے کوئی نام مطابقت نہیں رکھتا۔`, ben: `আপনার অনুসন্ধানের সাথে কোনো নাম মেলে না।`, fas: `هیچ نامی با جستجوی شما مطابقت ندارد.`, zh: `没有名字符合您的搜索。`, yue: `冇名字符合您嘅搜索。`, ja: `お探しの御名は見つかりませんでした。`, ru: `Нет имён, соответствующих вашему запросу.`, es: `Ningún nombre coincide con su búsqueda.`, ko: `검색과 일치하는 이름이 없습니다.`, ta: `உங்கள் தேடலுக்கு பொருந்தும் பெயர்கள் இல்லை.`, si: `ඔබේ සෙවීමට ගැළපෙන නාම නොමැත.` },
};
