/**
 * UI labels for the per-country PrayerTimesWidget.
 * Arabic stays hardcoded in the widget itself (city names are anglicised proper nouns).
 */

type LangMap = {
  en: string; ms: string; tur: string; urd: string; ben: string; fas: string;
  zh: string; yue: string; ja: string; ru: string; es: string; ko: string;
  ta: string; si: string;
};

export type PrayerWidgetKey = keyof typeof PRAYER_WIDGET_CONTENT;

export const PRAYER_WIDGET_CONTENT = {
  widget_h: { en: `Today's Prayer Times`, ms: `Waktu Solat Hari Ini`, tur: `Bugünün Namaz Vakitleri`, urd: `آج کے نماز کے اوقات`, ben: `আজকের নামাজের সময়`, fas: `اوقات نماز امروز`, zh: `今日拜功時間`, yue: `今日拜功時間`, ja: `今日の礼拝時刻`, ru: `Времена молитв на сегодня`, es: `Tiempos de oración de hoy`, ko: `오늘의 예배 시간`, ta: `இன்றைய தொழுகை நேரங்கள்`, si: `අද සලාත් වේලාවන්` },
  widget_subtitle: { en: `Calculated locally in your browser using the adhan astronomical library. No internet request, no tracking, no AI.`, ms: `Dihitung secara tempatan di pelayar anda menggunakan pustaka astronomi adhan. Tiada permintaan internet, tiada penjejakan, tiada AI.`, tur: `Tarayıcınızda adhan astronomi kütüphanesi ile yerel olarak hesaplanır. İnternet isteği yok, takip yok, yapay zeka yok.`, urd: `آپ کے براؤزر میں adhan فلکیاتی لائبریری استعمال کرتے ہوئے مقامی طور پر حساب کیا گیا۔ کوئی انٹرنیٹ درخواست نہیں، کوئی ٹریکنگ نہیں، کوئی AI نہیں۔`, ben: `adhan জ্যোতির্বিদ্যা লাইব্রেরি ব্যবহার করে আপনার ব্রাউজারে স্থানীয়ভাবে গণনা করা হয়েছে। কোনো ইন্টারনেট অনুরোধ নেই, কোনো ট্র্যাকিং নেই, কোনো AI নেই।`, fas: `با استفاده از کتابخانه نجومی adhan در مرورگر شما به‌صورت محلی محاسبه می‌شود. هیچ درخواست اینترنتی، هیچ ردیابی، هیچ هوش مصنوعی.`, zh: `使用 adhan 天文庫於您的瀏覽器本地計算。無網路請求，無追蹤，無 AI。`, yue: `使用 adhan 天文庫於您嘅瀏覽器本地計算。無網路請求，無追蹤，無 AI。`, ja: `adhan 天文ライブラリを使用してブラウザ内でローカルに計算されます。インターネット要求なし、追跡なし、AI なし。`, ru: `Вычисляется локально в вашем браузере с использованием астрономической библиотеки adhan. Никаких интернет-запросов, никакого отслеживания, никакого ИИ.`, es: `Calculado localmente en su navegador usando la biblioteca astronómica adhan. Sin solicitudes a internet, sin seguimiento, sin IA.`, ko: `adhan 천문학 라이브러리를 사용하여 브라우저에서 로컬로 계산됩니다. 인터넷 요청 없음, 추적 없음, AI 없음.`, ta: `adhan வானியல் நூலகத்தைப் பயன்படுத்தி உங்கள் உலாவியில் உள்ளூரில் கணக்கிடப்படுகிறது. இணைய கோரிக்கை இல்லை, கண்காணிப்பு இல்லை, AI இல்லை.`, si: `adhan තාරකා විද්‍යා පුස්තකාලය භාවිතයෙන් ඔබේ බ්‍රවුසරයේ දේශීයව ගණනය කරයි. අන්තර්ජාල ඉල්ලීමක් නැත, ලුහුබැඳීමක් නැත, AI නැත.` },
  label_city: { en: `City`, ms: `Bandar`, tur: `Şehir`, urd: `شہر`, ben: `শহর`, fas: `شهر`, zh: `城市`, yue: `城市`, ja: `都市`, ru: `Город`, es: `Ciudad`, ko: `도시`, ta: `நகரம்`, si: `නගරය` },
  label_method: { en: `Calculation method`, ms: `Kaedah pengiraan`, tur: `Hesaplama yöntemi`, urd: `حساب کا طریقہ`, ben: `গণনা পদ্ধতি`, fas: `روش محاسبه`, zh: `計算方法`, yue: `計算方法`, ja: `計算方法`, ru: `Метод расчёта`, es: `Método de cálculo`, ko: `계산 방법`, ta: `கணக்கீட்டு முறை`, si: `ගණනය ක්‍රමය` },
  label_asr: { en: `Asr juristic`, ms: `Mazhab Asar`, tur: `İkindi içtihadı`, urd: `عصر مذہبی`, ben: `আসর মাজহাব`, fas: `مذهب عصر`, zh: `晡禮教法`, yue: `晡禮教法`, ja: `アスル法学`, ru: `Аср мазхаб`, es: `Madhab del Asr`, ko: `아스르 법학`, ta: `அஸ்ர் சட்டம்`, si: `අසර් නීති` },
  asr_standard: { en: `Standard (Shafi'i/Maliki/Hanbali)`, ms: `Standard (Syafi'i/Maliki/Hanbali)`, tur: `Standart (Şâfiî/Mâlikî/Hanbelî)`, urd: `معیاری (شافعی/مالکی/حنبلی)`, ben: `স্ট্যান্ডার্ড (শাফিয়ি/মালিকি/হাম্বলি)`, fas: `استاندارد (شافعی/مالکی/حنبلی)`, zh: `標準（沙斐儀/馬立基/罕百里）`, yue: `標準（沙斐儀/馬立基/罕百里）`, ja: `標準（シャーフィイー/マーリキー/ハンバリー）`, ru: `Стандартный (Шафии/Малики/Ханбали)`, es: `Estándar (Shafi'i/Maliki/Hanbali)`, ko: `표준 (샤피이/말리키/한발리)`, ta: `தரநிலை (ஷாஃபிஈ/மாலிக்கி/ஹன்பலி)`, si: `සම්මත (ෂාෆිඊ/මාලිකී/හන්බලී)` },
  asr_hanafi: { en: `Hanafi`, ms: `Hanafi`, tur: `Hanefî`, urd: `حنفی`, ben: `হানাফি`, fas: `حنفی`, zh: `哈乃斐`, yue: `哈乃斐`, ja: `ハナフィー`, ru: `Ханафи`, es: `Hanafi`, ko: `하나피`, ta: `ஹனஃபி`, si: `හනෆී` },
  method_mwl: { en: `Muslim World League`, ms: `Liga Dunia Muslim`, tur: `İslam Dünyası Birliği`, urd: `مسلم ورلڈ لیگ`, ben: `মুসলিম ওয়ার্ল্ড লিগ`, fas: `اتحادیه جهان اسلام`, zh: `穆斯林世界聯盟`, yue: `穆斯林世界聯盟`, ja: `ムスリム世界連盟`, ru: `Лига исламского мира`, es: `Liga Mundial Musulmana`, ko: `이슬람 세계 연맹`, ta: `முஸ்லிம் உலக கூட்டமைப்பு`, si: `මුස්ලිම් ලෝක සංගමය` },
  method_egyptian: { en: `Egyptian General Authority`, ms: `Pihak Berkuasa Umum Mesir`, tur: `Mısır Genel Heyeti`, urd: `مصری جنرل اتھارٹی`, ben: `মিশরীয় সাধারণ কর্তৃপক্ষ`, fas: `سازمان عمومی مصر`, zh: `埃及天文總局`, yue: `埃及天文總局`, ja: `エジプト総局`, ru: `Египетское общее управление`, es: `Autoridad General de Egipto`, ko: `이집트 총국`, ta: `எகிப்திய பொது அதிகாரம்`, si: `ඊජිප්තු සාමාන්‍ය අධිකාරිය` },
  method_karachi: { en: `University of Islamic Sciences, Karachi`, ms: `Universiti Sains Islam, Karachi`, tur: `Karaçi İslâm İlimleri Üniversitesi`, urd: `یونیورسٹی آف اسلامک سائنسز، کراچی`, ben: `ইসলামিক বিজ্ঞান বিশ্ববিদ্যালয়, করাচি`, fas: `دانشگاه علوم اسلامی کراچی`, zh: `卡拉奇伊斯蘭科學大學`, yue: `卡拉奇伊斯蘭科學大學`, ja: `カラチイスラム科学大学`, ru: `Университет исламских наук, Карачи`, es: `Universidad de Ciencias Islámicas, Karachi`, ko: `카라치 이슬람 과학 대학교`, ta: `கராச்சி இஸ்லாமிய அறிவியல் பல்கலைக்கழகம்`, si: `කරාචි ඉස්ලාමීය විද්‍යා විශ්වවිද්‍යාලය` },
  method_uma: { en: `Umm al-Qura (Makkah)`, ms: `Umm al-Qura (Makkah)`, tur: `Ümmü'l-Kurâ (Mekke)`, urd: `ام القریٰ (مکہ)`, ben: `উম্মুল কুরা (মক্কা)`, fas: `ام القری (مکه)`, zh: `麥加母校大學`, yue: `麥加母校大學`, ja: `ウンム・アル＝クラー（マッカ）`, ru: `Умм аль-Кура (Мекка)`, es: `Umm al-Qura (La Meca)`, ko: `움 알꾸라 (메카)`, ta: `உம் அல்-குரா (மக்கா)`, si: `උම් අල්-කුරා (මක්කා)` },
  method_dubai: { en: `Dubai`, ms: `Dubai`, tur: `Dubai`, urd: `دبئی`, ben: `দুবাই`, fas: `دبی`, zh: `杜拜`, yue: `杜拜`, ja: `ドバイ`, ru: `Дубай`, es: `Dubái`, ko: `두바이`, ta: `துபாய்`, si: `ඩුබායි` },
  method_moonsighting: { en: `Moonsighting Committee`, ms: `Jawatankuasa Rukyah`, tur: `Hilal Gözlem Komitesi`, urd: `رویتِ ہلال کمیٹی`, ben: `চাঁদ দেখা কমিটি`, fas: `کمیته رؤیت هلال`, zh: `觀月委員會`, yue: `觀月委員會`, ja: `月観測委員会`, ru: `Комитет наблюдения за луной`, es: `Comité de Observación Lunar`, ko: `월광 관측 위원회`, ta: `சந்திர பார்வைக் குழு`, si: `සඳ දැකීමේ කමිටුව` },
  method_na: { en: `Islamic Society of North America`, ms: `Persatuan Islam Amerika Utara`, tur: `Kuzey Amerika İslam Cemiyeti`, urd: `اسلامی سوسائٹی آف نارتھ امریکہ`, ben: `উত্তর আমেরিকার ইসলামিক সোসাইটি`, fas: `انجمن اسلامی آمریکای شمالی`, zh: `北美伊斯蘭協會`, yue: `北美伊斯蘭協會`, ja: `北米イスラム協会`, ru: `Исламское общество Северной Америки`, es: `Sociedad Islámica de Norteamérica`, ko: `북미 이슬람 협회`, ta: `வட அமெரிக்க இஸ்லாமிய சங்கம்`, si: `උතුරු ඇමරිකානු ඉස්ලාමීය සංගමය` },
  method_kuwait: { en: `Kuwait`, ms: `Kuwait`, tur: `Kuveyt`, urd: `کویت`, ben: `কুয়েত`, fas: `کویت`, zh: `科威特`, yue: `科威特`, ja: `クウェート`, ru: `Кувейт`, es: `Kuwait`, ko: `쿠웨이트`, ta: `குவைத்`, si: `කුවේට්` },
  method_qatar: { en: `Qatar`, ms: `Qatar`, tur: `Katar`, urd: `قطر`, ben: `কাতার`, fas: `قطر`, zh: `卡達`, yue: `卡達`, ja: `カタール`, ru: `Катар`, es: `Catar`, ko: `카타르`, ta: `கத்தார்`, si: `කටාර්` },
  method_singapore: { en: `Singapore`, ms: `Singapura`, tur: `Singapur`, urd: `سنگاپور`, ben: `সিঙ্গাপুর`, fas: `سنگاپور`, zh: `新加坡`, yue: `新加坡`, ja: `シンガポール`, ru: `Сингапур`, es: `Singapur`, ko: `싱가포르`, ta: `சிங்கப்பூர்`, si: `සිංගප්පූරුව` },
  method_tehran: { en: `Tehran (Institute of Geophysics)`, ms: `Tehran (Institut Geofizik)`, tur: `Tahran (Jeofizik Enstitüsü)`, urd: `تہران (انسٹیٹیوٹ آف جیو فزکس)`, ben: `তেহরান (ইনস্টিটিউট অফ জিওফিজিক্স)`, fas: `تهران (مؤسسه ژئوفیزیک)`, zh: `德黑蘭（地球物理研究所）`, yue: `德黑蘭（地球物理研究所）`, ja: `テヘラン（地球物理学研究所）`, ru: `Тегеран (Институт геофизики)`, es: `Teherán (Instituto de Geofísica)`, ko: `테헤란 (지구물리학 연구소)`, ta: `தெஹ்ரான் (புவியியற்பியல் நிறுவனம்)`, si: `තෙහෙරාන් (භූභෞතික ආයතනය)` },
  method_turkey: { en: `Diyanet (Turkey)`, ms: `Diyanet (Turki)`, tur: `Diyanet (Türkiye)`, urd: `دیانت (ترکی)`, ben: `দিয়ানেত (তুরস্ক)`, fas: `دیانت (ترکیه)`, zh: `迪亞內特（土耳其）`, yue: `迪亞內特（土耳其）`, ja: `ディヤーネット（トルコ）`, ru: `Диянет (Турция)`, es: `Diyanet (Turquía)`, ko: `디야넷 (튀르키예)`, ta: `தியனேட் (துருக்கி)`, si: `දියනේත් (තුර්කිය)` },
  prayer_fajr: { en: `Fajr`, ms: `Subuh`, tur: `İmsak / Sabah`, urd: `فجر`, ben: `ফজর`, fas: `فجر`, zh: `晨禮`, yue: `晨禮`, ja: `ファジュル`, ru: `Фаджр`, es: `Fajr`, ko: `파즈르`, ta: `ஃபஜ்ர்`, si: `ෆජ්ර්` },
  prayer_sunrise: { en: `Sunrise`, ms: `Syuruk`, tur: `Güneş`, urd: `طلوع آفتاب`, ben: `সূর্যোদয়`, fas: `طلوع`, zh: `日出`, yue: `日出`, ja: `日の出`, ru: `Восход`, es: `Salida del sol`, ko: `일출`, ta: `சூரிய உதயம்`, si: `හිරු උදාව` },
  prayer_dhuhr: { en: `Dhuhr`, ms: `Zohor`, tur: `Öğle`, urd: `ظہر`, ben: `যোহর`, fas: `ظهر`, zh: `晌禮`, yue: `晌禮`, ja: `ズフル`, ru: `Зухр`, es: `Dhuhr`, ko: `주흐르`, ta: `துஹ்ர்`, si: `දුහර්` },
  prayer_asr: { en: `Asr`, ms: `Asar`, tur: `İkindi`, urd: `عصر`, ben: `আসর`, fas: `عصر`, zh: `晡禮`, yue: `晡禮`, ja: `アスル`, ru: `Аср`, es: `Asr`, ko: `아스르`, ta: `அஸ்ர்`, si: `අසර්` },
  prayer_maghrib: { en: `Maghrib`, ms: `Maghrib`, tur: `Akşam`, urd: `مغرب`, ben: `মাগরিব`, fas: `مغرب`, zh: `昏禮`, yue: `昏禮`, ja: `マグリブ`, ru: `Магриб`, es: `Maghrib`, ko: `마그립`, ta: `மக்ரிப்`, si: `මග්රිබ්` },
  prayer_isha: { en: `Isha`, ms: `Isyak`, tur: `Yatsı`, urd: `عشاء`, ben: `ইশা`, fas: `عشاء`, zh: `宵禮`, yue: `宵禮`, ja: `イシャー`, ru: `Иша`, es: `Isha`, ko: `이샤`, ta: `இஷா`, si: `ඉෂා` },
  next_prayer: { en: `Next prayer`, ms: `Solat berikutnya`, tur: `Sonraki namaz`, urd: `اگلی نماز`, ben: `পরবর্তী নামাজ`, fas: `نماز بعدی`, zh: `下一拜功`, yue: `下一拜功`, ja: `次の礼拝`, ru: `Следующая молитва`, es: `Próxima oración`, ko: `다음 예배`, ta: `அடுத்த தொழுகை`, si: `ඊළඟ සලාතය` },
  geolocate: { en: `Use my location`, ms: `Guna lokasi saya`, tur: `Konumumu kullan`, urd: `میری لوکیشن استعمال کریں`, ben: `আমার অবস্থান ব্যবহার করুন`, fas: `از موقعیت من استفاده کن`, zh: `使用我的位置`, yue: `使用我的位置`, ja: `現在地を使用`, ru: `Использовать моё местоположение`, es: `Usar mi ubicación`, ko: `내 위치 사용`, ta: `என் இருப்பிடத்தைப் பயன்படுத்து`, si: `මගේ ස්ථානය භාවිතා කරන්න` },
  location_using: { en: `Using your detected location`, ms: `Menggunakan lokasi yang dikesan`, tur: `Tespit edilen konumunuz kullanılıyor`, urd: `آپ کی پکڑی گئی لوکیشن استعمال ہو رہی ہے`, ben: `আপনার সনাক্ত করা অবস্থান ব্যবহার করা হচ্ছে`, fas: `از موقعیت تشخیص داده شده شما استفاده می‌شود`, zh: `使用您偵測到的位置`, yue: `使用您偵測到的位置`, ja: `検出された現在地を使用中`, ru: `Используется ваше определённое местоположение`, es: `Usando tu ubicación detectada`, ko: `감지된 위치 사용 중`, ta: `கண்டறியப்பட்ட இருப்பிடம் பயன்படுத்தப்படுகிறது`, si: `හඳුනාගත් ඔබේ ස්ථානය භාවිතා කරයි` },
  in_text: { en: `in`, ms: `dalam`, tur: `kalanı`, urd: `میں`, ben: `মধ্যে`, fas: `در`, zh: `還有`, yue: `仲有`, ja: `あと`, ru: `через`, es: `en`, ko: `후`, ta: `இல்`, si: `තුළ` },
  hours_short: { en: `h`, ms: `j`, tur: `s`, urd: `گ`, ben: `ঘ`, fas: `س`, zh: `時`, yue: `時`, ja: `時`, ru: `ч`, es: `h`, ko: `시`, ta: `ம`, si: `පැ` },
  minutes_short: { en: `m`, ms: `m`, tur: `dk`, urd: `م`, ben: `মি`, fas: `د`, zh: `分`, yue: `分`, ja: `分`, ru: `м`, es: `m`, ko: `분`, ta: `நி`, si: `මි` },
} satisfies Record<string, LangMap>;
