type LangMap = { en: string; ms: string; tur: string; urd: string; ben: string; fas: string; zh: string; yue: string; ja: string; ru: string; es: string; ko: string; ta?: string; si?: string };
export type RamadanContentKey = keyof typeof RAMADAN_CONTENT;

export const RAMADAN_CONTENT = {
  section_prescribed: { en: 'Why Ramadan Was Prescribed', ms: 'Mengapa Ramadan Diwajibkan', tur: 'Ramazan Neden Farz Kılındı', urd: 'رمضان کیوں فرض کیا گیا', ben: 'কেন রমজান নির্ধারিত হয়েছিল', fas: 'چرا رمضان واجب شد', zh: '斋月为何被规定', yue: '齋月為何被規定', ja: 'ラマダーンが定められた理由', ru: 'Почему был предписан Рамадан', es: 'Por Qué se Prescribió el Ramadán', ko: '라마단이 규정된 이유' },
  section_hilal: { en: 'The Hilal: Beginning the Month', ms: 'Anak Bulan: Memulakan Bulan', tur: 'Hilal: Ayın Başlangıcı', urd: 'ہلال: مہینے کا آغاز', ben: 'হিলাল: মাসের শুরু', fas: 'هلال: آغاز ماه', zh: '新月：月份的开始', yue: '新月：月份嘅開始', ja: 'ヒラール：月の始まり', ru: 'Полумесяц: начало месяца', es: 'El Hilal: Comienzo del Mes', ko: '초승달: 달의 시작' },
  section_conditions: { en: 'Upon Whom is Fasting Obligatory?', ms: 'Ke atas Siapakah Puasa Wajib?', tur: 'Oruç Kime Farz?', urd: 'روزہ کس پر فرض ہے؟', ben: 'কার উপর রোজা ফরজ?', fas: 'روزه بر چه کسانی واجب است؟', zh: '斋戒对谁是义务？', yue: '齋戒對誰係義務？', ja: 'だれに断食は義務ですか？', ru: 'На кого обязателен пост?', es: '¿Sobre Quién es Obligatorio el Ayuno?', ko: '누구에게 단식이 의무인가?' },
  section_invalidators: { en: 'What Breaks the Fast and What Does Not', ms: 'Apa yang Membatalkan Puasa dan Apa yang Tidak', tur: 'Orucu Bozan ve Bozmayan Şeyler', urd: 'کیا چیز روزہ توڑتی ہے اور کیا نہیں', ben: 'কী রোজা ভাঙে এবং কী ভাঙে না', fas: 'آنچه روزه را می‌شکند و آنچه نمی‌شکند', zh: '破斋与不破斋的事项', yue: '破齋與不破齋嘅事項', ja: '断食を破るものとそうでないもの', ru: 'Что нарушает пост и что — нет', es: 'Qué Rompe el Ayuno y Qué No', ko: '단식을 깨는 것과 그렇지 않은 것' },
  section_suhur_iftar: { en: 'Suhur and Iftar', ms: 'Sahur dan Iftar', tur: 'Sahur ve İftar', urd: 'سحری اور افطار', ben: 'সেহরি ও ইফতার', fas: 'سحر و افطار', zh: '封斋前餐与开斋', yue: '封齋前餐與開齋', ja: 'スフールとイフタール', ru: 'Сухур и Ифтар', es: 'Suhur e Iftar', ko: '수후르와 이프타르' },
  section_taraweeh: { en: 'Taraweeh: The Night Prayer of Ramadan', ms: 'Tarawih: Solat Malam Ramadan', tur: 'Teravih: Ramazanın Gece Namazı', urd: 'تراویح: رمضان کی رات کی نماز', ben: 'তারাবিহ: রমজানের রাতের নামাজ', fas: 'تراویح: نماز شب رمضان', zh: '塔拉威哈：斋月的夜礼拜', yue: '塔拉威哈：齋月嘅夜禮拜', ja: 'タラーウィーフ：ラマダーンの夜礼拝', ru: 'Таравих: ночная молитва Рамадана', es: 'Taraweeh: La Oración Nocturna de Ramadán', ko: '타라위흐: 라마단의 야간 예배' },
  section_laylatul_qadr: { en: 'Laylatul Qadr: The Night of Power', ms: 'Lailatul Qadar: Malam Kemuliaan', tur: 'Kadir Gecesi: Güç Gecesi', urd: 'لیلۃ القدر: شب قدر', ben: 'লাইলাতুল কদর: ক্ষমতার রাত', fas: 'لیله‌القدر: شب قدر', zh: '盖德尔夜：威能之夜', yue: '蓋德爾夜：威能之夜', ja: 'ライラトゥル・カドル：力の夜', ru: 'Лайлатуль-Кадр: Ночь Могущества', es: 'Laylatul Qadr: La Noche del Poder', ko: '라일라툴 카드르: 권능의 밤' },
  section_itikaf: { en: "I'tikaf: Seclusion in the Mosque", ms: "I'tikaf: Berkhalwat di Masjid", tur: "İtikaf: Mescitte İnziva", urd: 'اعتکاف: مسجد میں خلوت', ben: 'ইতিকাফ: মসজিদে একাকিত্ব', fas: 'اعتکاف: خلوت در مسجد', zh: '闭关：在清真寺中隐居', yue: '閉關：在清真寺中隱居', ja: 'イティカーフ：モスクでの篭もり', ru: 'Итикаф: уединение в мечети', es: "I'tikaf: Reclusión en la Mezquita", ko: '이티카프: 모스크에서의 고립' },
  section_zakat_fitr: { en: 'Zakat al-Fitr: The Obligatory End-of-Ramadan Charity', ms: 'Zakat Fitrah: Sedekah Wajib Akhir Ramadan', tur: 'Fitre: Ramazan Sonu Zorunlu Zekat', urd: 'زکاۃ الفطر: رمضان کے آخر کی لازمی زکاۃ', ben: 'যাকাতুল ফিতর: রমজানের শেষের বাধ্যতামূলক দান', fas: 'زکات فطر: صدقه واجب پایان رمضان', zh: '开斋捐：斋月末强制慈善', yue: '開齋捐：齋月末強制慈善', ja: 'ザカートゥル・フィトル：ラマダーン末の義務的喜捨', ru: 'Закят аль-Фитр: обязательная милостыня в конце Рамадана', es: 'Zakat al-Fitr: La Caridad Obligatoria al Final del Ramadán', ko: '자카트 알피트르: 라마단 말 의무 자선' },
  section_eid: { en: 'Eid al-Fitr: The Celebration of Breaking the Fast', ms: 'Eid al-Fitr: Perayaan Berbuka Puasa', tur: 'Ramazan Bayramı: Oruç Bozmanın Kutlaması', urd: 'عید الفطر: روزوں کے اختتام کی خوشی', ben: 'ঈদুল ফিতর: রোজা শেষের উৎসব', fas: 'عید فطر: جشن پایان روزه', zh: '开斋节：斋戒庆典', yue: '開齋節：齋戒慶典', ja: 'イードゥル・フィトル：断食終了の祝い', ru: 'Ид аль-Фитр: праздник разговения', es: 'Eid al-Fitr: La Celebración del Fin del Ayuno', ko: '이드 알피트르: 단식 종료 축제' },
  section_spiritual: { en: 'The Spiritual Wisdom of Ramadan', ms: 'Hikmah Rohani Ramadan', tur: 'Ramazanın Manevi Hikmeti', urd: 'رمضان کی روحانی حکمت', ben: 'রমজানের আধ্যাত্মিক জ্ঞান', fas: 'حکمت معنوی رمضان', zh: '斋月的精神智慧', yue: '齋月嘅精神智慧', ja: 'ラマダーンの精神的な知恵', ru: 'Духовная мудрость Рамадана', es: 'La Sabiduría Espiritual del Ramadán', ko: '라마단의 정신적 지혜' },

  label_transliteration: { en: 'Transliteration', ms: 'Transliterasi', tur: 'Okunuş', urd: 'تلفظ', ben: 'উচ্চারণ', fas: 'نویسه‌گردانی', zh: '转写', yue: '轉寫', ja: '音写', ru: 'Транслитерация', es: 'Transliteración', ko: '로마자 표기' },
  label_meaning: { en: 'Meaning', ms: 'Makna', tur: 'Anlam', urd: 'معنی', ben: 'অর্থ', fas: 'معنا', zh: '含义', yue: '含義', ja: '意味', ru: 'Значение', es: 'Significado', ko: '의미' },
  label_invalidators_heading: { en: 'Invalidators of the Fast', ms: 'Perkara yang Membatalkan Puasa', tur: 'Orucu Bozan Şeyler', urd: 'روزہ توڑنے والی چیزیں', ben: 'রোজা ভাঙার কারণ', fas: 'مبطلات روزه', zh: '使斋戒无效的事项', yue: '使齋戒無效嘅事項', ja: '断食を無効にするもの', ru: 'Нарушители поста', es: 'Invalidadores del Ayuno', ko: '단식을 무효로 하는 것' },
  label_does_not_break: { en: 'What Does NOT Break the Fast', ms: 'Apa yang TIDAK Membatalkan Puasa', tur: 'Orucu BOZMAYANLAR', urd: 'جو روزہ نہیں توڑتا', ben: 'যা রোজা ভাঙে না', fas: 'آنچه روزه را نمی‌شکند', zh: '不破斋的事项', yue: '不破齋嘅事項', ja: '断食を破らないもの', ru: 'Что НЕ нарушает пост', es: 'Lo que NO Rompe el Ayuno', ko: '단식을 깨지 않는 것' },
  label_signs: { en: 'Signs of Laylatul Qadr', ms: 'Tanda-tanda Lailatul Qadar', tur: 'Kadir Gecesinin Alametleri', urd: 'لیلۃ القدر کی نشانیاں', ben: 'লাইলাতুল কদরের চিহ্ন', fas: 'نشانه‌های لیله‌القدر', zh: '盖德尔夜的迹象', yue: '蓋德爾夜嘅跡象', ja: 'ライラトゥル・カドルのしるし', ru: 'Признаки Лайлатуль-Кадр', es: 'Señales de la Laylatul Qadr', ko: '라일라툴 카드르의 징조' },
  label_itikaf_conditions: { en: 'Conditions and Rules', ms: 'Syarat dan Hukum', tur: 'Şartlar ve Kurallar', urd: 'شرائط اور احکام', ben: 'শর্তাবলী ও বিধান', fas: 'شرایط و احکام', zh: '条件与规则', yue: '條件與規則', ja: '条件とルール', ru: 'Условия и правила', es: 'Condiciones y Reglas', ko: '조건과 규칙' },
  label_dua_iftar: { en: 'Dua When Breaking the Fast', ms: 'Doa Ketika Berbuka', tur: 'İftar Duası', urd: 'افطار کی دعا', ben: 'ইফতারের সময় দোয়া', fas: 'دعای افطار', zh: '开斋时的祈祷', yue: '開齋時嘅祈禱', ja: 'イフタール時のドゥアー', ru: 'Дуа при разговении', es: 'Dua al Romper el Ayuno', ko: '이프타르 때 두아' },
  label_dua_alternative: { en: 'Alternative Dua', ms: 'Doa Alternatif', tur: 'Alternatif Dua', urd: 'متبادل دعا', ben: 'বিকল্প দোয়া', fas: 'دعای جایگزین', zh: '备选祈祷', yue: '備選祈禱', ja: '別のドゥアー', ru: 'Альтернативная дуа', es: 'Dua Alternativa', ko: '대체 두아' },
  label_dua_laylatul_qadr: { en: "The Prophet's Recommended Dua for Laylatul Qadr", ms: 'Doa yang Disyorkan Nabi ﷺ untuk Lailatul Qadar', tur: "Peygamberin ﷺ Kadir Gecesi için Tavsiye Ettiği Dua", urd: 'لیلۃ القدر کے لیے نبیؐ کی تجویز کردہ دعا', ben: 'লাইলাতুল কদরের জন্য নবীর ﷺ সুপারিশকৃত দোয়া', fas: 'دعای توصیه‌شده پیامبر ﷺ برای لیله‌القدر', zh: '先知ﷺ为盖德尔夜推荐的祈祷', yue: '先知ﷺ為蓋德爾夜推薦嘅祈禱', ja: '預言者ﷺがライラトゥル・カドルに勧めるドゥアー', ru: 'Рекомендованная Пророком ﷺ дуа в Лайлатуль-Кадр', es: 'La Dua Recomendada por el Profeta ﷺ para Laylatul Qadr', ko: '라일라툴 카드르를 위해 예언자ﷺ가 권장한 두아' },

  suhur_title: { en: 'Suhur: The Pre-Dawn Meal', ms: 'Sahur: Makan Sebelum Subuh', tur: 'Sahur: Seher Yemeği', urd: 'سحری: سحر کا کھانا', ben: 'সেহরি: ফজরের আগের খাবার', fas: 'سحر: وعده پیش از فجر', zh: '封斋前餐', yue: '封齋前餐', ja: 'スフール：夜明け前の食事', ru: 'Сухур: предрассветная трапеза', es: 'Suhur: La Comida Antes del Amanecer', ko: '수후르: 새벽 전 식사' },
  iftar_title: { en: 'Iftar: Breaking the Fast', ms: 'Iftar: Berbuka Puasa', tur: 'İftar: Oruç Açmak', urd: 'افطار: روزہ افطار کرنا', ben: 'ইফতার: রোজা ভাঙা', fas: 'افطار: گشودن روزه', zh: '开斋', yue: '開齋', ja: 'イフタール：断食の終わり', ru: 'Ифтар: разговение', es: 'Iftar: Romper el Ayuno', ko: '이프타르: 단식 해제' },
  taraweeh_8: { en: "8 Units (Rak'ahs)", ms: "8 Rakaat", tur: "8 Rekat", urd: '۸ رکعات', ben: '৮ রাকাআত', fas: '۸ رکعت', zh: '8 拜', yue: '8 拜', ja: '8 ラクア', ru: '8 ракатов', es: '8 Unidades (Rak\'ahs)', ko: '8 라카아' },
  taraweeh_20: { en: "20 Units (Rak'ahs)", ms: "20 Rakaat", tur: "20 Rekat", urd: '۲۰ رکعات', ben: '২০ রাকাআত', fas: '۲۰ رکعت', zh: '20 拜', yue: '20 拜', ja: '20 ラクア', ru: '20 ракатов', es: "20 Unidades (Rak'ahs)", ko: '20 라카아' },

  cond_muslim: { en: 'Muslim', ms: 'Muslim', tur: 'Müslüman', urd: 'مسلمان', ben: 'মুসলিম', fas: 'مسلمان', zh: '穆斯林', yue: '穆斯林', ja: 'ムスリム', ru: 'Мусульманин', es: 'Musulmán', ko: '무슬림' },
  cond_adult: { en: 'Adult (Baligh)', ms: 'Baligh', tur: 'Ergen (Baligh)', urd: 'بالغ', ben: 'বালিগ (প্রাপ্তবয়স্ক)', fas: 'بالغ', zh: '成年人（巴利格）', yue: '成年人（巴利格）', ja: '成人（バーリグ）', ru: 'Совершеннолетний (Балиг)', es: 'Adulto (Baligh)', ko: '성인 (발리그)' },
  cond_sane: { en: 'Sane (Aaqil)', ms: 'Berakal', tur: 'Akıl Sahibi', urd: 'عاقل', ben: 'বিবেকবান (আকিল)', fas: 'عاقل', zh: '理智（正常人）', yue: '理智（正常人）', ja: '正気（アーキル）', ru: 'Разумный (Акиль)', es: 'Cuerdo (Aaqil)', ko: '정신이 건강한 사람 (아킬)' },
  cond_healthy: { en: 'Healthy', ms: 'Sihat', tur: 'Sağlıklı', urd: 'صحت مند', ben: 'সুস্থ', fas: 'سالم', zh: '健康', yue: '健康', ja: '健康', ru: 'Здоровый', es: 'Sano', ko: '건강한' },
  cond_resident: { en: 'Resident (not travelling)', ms: 'Muqim (tidak bermusafir)', tur: 'Mukim (seyahatte değil)', urd: 'مقیم (مسافر نہیں)', ben: 'স্থানীয় (ভ্রমণকারী নয়)', fas: 'مقیم (مسافر نیست)', zh: '居民（非旅行者）', yue: '居民（非旅行者）', ja: '居住者（旅人でない）', ru: 'Житель (не путешественник)', es: 'Residente (no viajero)', ko: '거주자 (여행 중이 아닌)' },
  cond_capable: { en: 'Capable (not pregnant or nursing)', ms: 'Mampu (tidak hamil atau menyusu)', tur: 'Güçlü (hamile veya emzirmiyor)', urd: 'قادر (حاملہ یا دودھ پلانے والی نہیں)', ben: 'সক্ষম (গর্ভবতী বা বুকের দুধ খাওয়াচ্ছেন না)', fas: 'قادر (باردار یا شیرده نیست)', zh: '有能力（未怀孕或哺乳）', yue: '有能力（未懷孕或哺乳）', ja: '能力あり（妊娠中や授乳中でない）', ru: 'Способный (не беременная и не кормящая)', es: 'Capaz (no embarazada ni lactando)', ko: '능력 있는 (임신 중이거나 수유 중이 아닌)' },

  inv_1: { en: 'Eating or drinking intentionally', ms: 'Makan atau minum dengan sengaja', tur: 'Kasıtlı yiyip içmek', urd: 'جان بوجھ کر کھانا یا پینا', ben: 'ইচ্ছাকৃতভাবে খাওয়া বা পান করা', fas: 'خوردن یا آشامیدن عمدی', zh: '故意饮食', yue: '故意飲食', ja: '意図的な飲食', ru: 'Намеренное употребление пищи или воды', es: 'Comer o beber intencionalmente', ko: '의도적으로 먹거나 마시기' },
  inv_2: { en: 'Sexual intercourse', ms: 'Bersetubuh', tur: 'Cinsel ilişki', urd: 'جماع', ben: 'যৌন সংসর্গ', fas: 'نزدیکی', zh: '性交', yue: '性交', ja: '性交', ru: 'Половой акт', es: 'Relación sexual', ko: '성교' },
  inv_3: { en: 'Intentional vomiting', ms: 'Muntah dengan sengaja', tur: 'Kasıtlı kusma', urd: 'جان بوجھ کر قے کرنا', ben: 'ইচ্ছাকৃত বমি', fas: 'استفراغ عمدی', zh: '故意呕吐', yue: '故意嘔吐', ja: '意図的な嘔吐', ru: 'Намеренная рвота', es: 'Vómito intencional', ko: '의도적인 구토' },
  inv_4: { en: 'Menstruation or post-natal bleeding', ms: 'Haid atau nifas', tur: 'Hayız veya nifas', urd: 'حیض یا نفاس', ben: 'মাসিক বা প্রসব-পরবর্তী রক্তক্ষরণ', fas: 'حیض یا نفاس', zh: '月经或产后出血', yue: '月經或產後出血', ja: '月経または産後出血', ru: 'Менструация или послеродовое кровотечение', es: 'Menstruación o sangrado posparto', ko: '생리 또는 산후 출혈' },
  inv_5: { en: 'Masturbation leading to emission', ms: 'Onani hingga keluar air mani', tur: 'Boşalmaya yol açan mastürbasyon', urd: 'انزال تک پہنچنے والا استمناء', ben: 'বীর্যপাতসহ হস্তমৈথুন', fas: 'استمنا منجر به انزال', zh: '导致射精的手淫', yue: '導致射精的手淫', ja: '射精を伴う自慰', ru: 'Онанизм с семяизвержением', es: 'Masturbación con emisión', ko: '사정을 동반한 자위' },
  inv_6: { en: 'Deliberate apostasy from Islam', ms: 'Murtad dengan sengaja', tur: 'Kasıtlı irtidat', urd: 'جان بوجھ کر ارتداد', ben: 'ইচ্ছাকৃত ধর্মত্যাগ', fas: 'ارتداد عمدی از اسلام', zh: '故意叛教', yue: '故意叛教', ja: '意図的な背教', ru: 'Намеренное отступничество от Ислама', es: 'Apostasía deliberada del Islam', ko: '의도적인 이슬람 배교' },

  spiritual_1_title: { en: 'Taqwa: The Goal of Fasting', ms: 'Taqwa: Matlamat Berpuasa', tur: 'Takva: Orucun Hedefi', urd: 'تقویٰ: روزے کا مقصد', ben: 'তাকওয়া: রোজার লক্ষ্য', fas: 'تقوا: هدف روزه', zh: '虔诚：封斋的目标', yue: '虔誠：封齋嘅目標', ja: 'タクワー：断食の目標', ru: 'Такуа: цель поста', es: 'Taqwa: El Objetivo del Ayuno', ko: '타크와: 단식의 목표' },
  spiritual_2_title: { en: 'Gratitude Through Hunger', ms: 'Syukur Melalui Kelaparan', tur: 'Açlık Yoluyla Şükür', urd: 'بھوک کے ذریعے شکر', ben: 'ক্ষুধার মাধ্যমে কৃতজ্ঞতা', fas: 'سپاسگزاری از طریق گرسنگی', zh: '通过饥饿而感恩', yue: '通過饑餓而感恩', ja: '飢えによる感謝', ru: 'Благодарность через голод', es: 'Gratitud a Través del Hambre', ko: '굶주림을 통한 감사' },
  spiritual_3_title: { en: 'Empathy with the Poor', ms: 'Empati dengan Si Miskin', tur: 'Yoksullarla Empati', urd: 'غریبوں سے ہمدردی', ben: 'দরিদ্রদের প্রতি সহানুভূতি', fas: 'همدلی با فقرا', zh: '对穷人的同理心', yue: '對窮人嘅同理心', ja: '貧しい人々への共感', ru: 'Сочувствие к бедным', es: 'Empatía con los Pobres', ko: '가난한 이들에 대한 공감' },
  spiritual_4_title: { en: 'The Month of the Quran', ms: 'Bulan al-Quran', tur: "Kuran'ın Ayı", urd: 'قرآن کا مہینہ', ben: 'কুরআনের মাস', fas: 'ماه قرآن', zh: '古兰经之月', yue: '古蘭經之月', ja: 'クルアーンの月', ru: 'Месяц Корана', es: 'El Mes del Corán', ko: '쿠란의 달' },

  zakat_label_amount: { en: 'Amount', ms: 'Jumlah', tur: 'Miktar', urd: 'مقدار', ben: 'পরিমাণ', fas: 'مقدار', zh: '数量', yue: '數量', ja: '量', ru: 'Размер', es: 'Cantidad', ko: '수량' },
  zakat_label_who_pays: { en: 'Who Pays', ms: 'Siapa Membayar', tur: 'Kim Öder', urd: 'کون ادا کرتا ہے', ben: 'কে দেয়', fas: 'چه کسی می‌پردازد', zh: '谁来缴纳', yue: '誰來繳納', ja: '誰が払うか', ru: 'Кто платит', es: 'Quién Paga', ko: '누가 납부하나' },
  zakat_label_who_receives: { en: 'Who Receives', ms: 'Siapa Menerima', tur: 'Kim Alır', urd: 'کون وصول کرتا ہے', ben: 'কে পায়', fas: 'چه کسی دریافت می‌کند', zh: '谁来接受', yue: '誰來接受', ja: '誰が受け取るか', ru: 'Кто получает', es: 'Quién Recibe', ko: '누가 받나' },
  zakat_label_when: { en: 'When to Pay', ms: 'Bila Membayar', tur: 'Ne Zaman Ödenir', urd: 'کب ادا کریں', ben: 'কখন দিতে হবে', fas: 'چه زمانی بپردازید', zh: '何时缴纳', yue: '何時繳納', ja: 'いつ払うか', ru: 'Когда платить', es: 'Cuándo Pagar', ko: '언제 납부하나' },

  closing_hadith: { en: '"When Ramadan enters, the gates of Paradise are opened, the gates of Hell are closed, and the devils are chained."', ms: '"Apabila Ramadan masuk, pintu-pintu syurga dibuka, pintu-pintu neraka ditutup dan syaitan-syaitan dibelenggu."', tur: '"Ramazan girince cennetin kapıları açılır, cehennemin kapıları kapanır ve şeytanlar zincire vurulur."', urd: '"جب رمضان آتا ہے تو جنت کے دروازے کھول دیے جاتے ہیں، جہنم کے دروازے بند کر دیے جاتے ہیں اور شیاطین جکڑ دیے جاتے ہیں۔"', ben: '"রমজান এলে জান্নাতের দরজাগুলো খুলে দেওয়া হয়, জাহান্নামের দরজাগুলো বন্ধ করা হয় এবং শয়তানদের শিকল দিয়ে বাঁধা হয়।"', fas: '"وقتی رمضان داخل می‌شود، درهای بهشت گشوده می‌شود، درهای دوزخ بسته می‌شود و شیاطین به زنجیر کشیده می‌شوند."', zh: '"斋月到来时，天堂的大门打开，地狱的大门关闭，魔鬼被锁链镣铐。"', yue: '"齋月到來時，天堂嘅大門打開，地獄嘅大門關閉，魔鬼被鎖鏈鐐銬。"', ja: '"ラマダーンが来ると、楽園の門が開かれ、地獄の門が閉じられ、悪魔が鎖に繋がれる。"', ru: '"Когда наступает Рамадан, открываются врата Рая, закрываются врата Ада, и дьяволы заковываются в цепи."', es: '"Cuando entra el Ramadán, las puertas del Paraíso se abren, las puertas del Infierno se cierran, y los diablos son encadenados."', ko: '"라마단이 오면 낙원의 문들이 열리고, 지옥의 문들이 닫히며, 악마들은 사슬에 묶인다."' },
  closing_source: { en: 'Bukhari 1899, Muslim 1079, narrated by Abu Hurairah (ra)', ms: 'Bukhari 1899, Muslim 1079, diriwayatkan oleh Abu Hurairah (ra)', tur: 'Buhari 1899, Müslim 1079, Ebu Hureyre (ra) rivayet etti', urd: 'بخاری ۱۸۹۹، مسلم ۱۰۷۹، ابوہریرہ رضی اللہ عنہ سے روایت', ben: 'বুখারি ১৮৯৯, মুসলিম ১০৭৯, আবু হুরায়রা (রা) থেকে বর্ণিত', fas: 'بخاری ۱۸۹۹، مسلم ۱۰۷۹، روایت ابوهریره (رضی‌الله‌عنه)', zh: '布哈里1899，穆斯林1079，据艾布·胡莱勒（愿主喜悦之）传述', yue: '布哈里1899，穆斯林1079，據艾布·胡莱勒（願主喜悅之）傳述', ja: 'ブハーリー1899、ムスリム1079、アブー・フライラ（彼に御満悦あれ）伝', ru: 'Бухари 1899, Муслим 1079, со слов Абу Хурайры (да будет доволен им Аллах)', es: 'Bujari 1899, Muslim 1079, narrado por Abu Hurairah (que Allah esté complacido con él)', ko: '부하리 1899, 무슬림 1079, 아부 후라이라(알라께서 그를 기뻐하시길) 전달' },
} satisfies Record<string, LangMap>;
