type LangMap = { en: string; ms: string; tur: string; urd: string; ben: string; fas: string; zh: string; yue: string; ja: string; ru: string; es: string; ko: string; ta?: string; si?: string };
export type TawheedContentKey = keyof typeof TAWHEED_CONTENT;

export const TAWHEED_CONTENT = {
  page_title: { en: 'Tawheed: Divine Oneness', ms: 'Tauhid: Keesaan Ilahi', tur: 'Tevhid: İlahi Birlik', urd: 'توحید: الہی وحدانیت', ben: 'তাওহীদ: ঐশী একত্ব', fas: 'توحید: یگانگی الهی', zh: '认主独一：神圣独一', yue: '認主獨一：神聖獨一', ja: 'タウヒード：神の唯一性', ru: 'Таухид: Единобожие', es: 'Tawheed: Unicidad Divina', ko: '타위드: 신성한 유일성' },
  page_subtitle: { en: 'Tawheed is the cornerstone of Islam: the first message of every prophet, the first question in the grave, and the decisive matter on the Day of Judgement.', ms: 'Tauhid adalah asas Islam: mesej pertama setiap nabi, soalan pertama di dalam kubur, dan perkara penentu pada Hari Kiamat.', tur: 'Tevhid İslam\'ın temel taşıdır: her peygamberin ilk mesajı, kabirdeki ilk soru ve Kıyamet Günü\'ndeki belirleyici mesele.', urd: 'توحید اسلام کی بنیاد ہے: ہر نبی کا پہلا پیغام، قبر میں پہلا سوال، اور قیامت کے دن فیصلہ کن معاملہ۔', ben: 'তাওহীদ ইসলামের মূল ভিত্তি: প্রতিটি নবীর প্রথম বার্তা, কবরে প্রথম প্রশ্ন, এবং কিয়ামতের দিন চূড়ান্ত বিষয়।', fas: 'توحید سنگ بنای اسلام است: نخستین پیام هر پیامبر، نخستین پرسش در قبر، و مسئله سرنوشت‌ساز روز قیامت.', zh: '认主独一是伊斯兰的基石：每位先知的第一条信息，坟墓中的第一个问题，以及末日审判的决定性事项。', yue: '認主獨一係伊斯蘭嘅基石：每位先知嘅第一條信息，墳墓中嘅第一個問題，以及末日審判嘅決定性事項。', ja: 'タウヒードはイスラームの礎石：全ての預言者の最初のメッセージ、墓の中での最初の質問、そして審判の日の決定的な事柄。', ru: 'Таухид  –  краеугольный камень Ислама: первое послание каждого пророка, первый вопрос в могиле и решающий вопрос Судного дня.', es: 'El Tawheed es la piedra angular del Islam: el primer mensaje de cada profeta, la primera pregunta en la tumba y el asunto decisivo en el Día del Juicio.', ko: '타위드는 이슬람의 초석입니다: 모든 예언자의 첫 번째 메시지, 무덤에서의 첫 번째 질문, 그리고 심판의 날의 결정적인 사항.' },

  section_whatIs: { en: 'What is Tawheed?', ms: 'Apakah Tauhid?', tur: 'Tevhid Nedir?', urd: 'توحید کیا ہے؟', ben: 'তাওহীদ কী?', fas: 'توحید چیست؟', zh: '什么是认主独一？', yue: '乜嘢係認主獨一？', ja: 'タウヒードとは何ですか？', ru: 'Что такое Таухид?', es: '¿Qué es el Tawheed?', ko: '타위드란 무엇인가?' },
  section_three: { en: 'The Three Categories of Tawheed', ms: 'Tiga Bahagian Tauhid', tur: 'Tevhidin Üç Kategorisi', urd: 'توحید کی تین اقسام', ben: 'তাওহীদের তিনটি বিভাগ', fas: 'سه قسم توحید', zh: '认主独一的三个类别', yue: '認主獨一嘅三個類別', ja: 'タウヒードの三つのカテゴリー', ru: 'Три категории Таухида', es: 'Las Tres Categorías del Tawheed', ko: '타위드의 세 가지 범주' },
  section_shahada: { en: 'The Shahada and Its Conditions', ms: 'Syahadah dan Syarat-syaratnya', tur: 'Şehadet ve Şartları', urd: 'شہادت اور اس کی شرائط', ben: 'শাহাদা ও তার শর্তাবলী', fas: 'شهادت و شرایط آن', zh: '清真言及其条件', yue: '清真言及其條件', ja: 'シャハーダとその条件', ru: 'Шахада и её условия', es: 'La Shahada y Sus Condiciones', ko: '샤하다와 그 조건' },
  section_keyVerses: { en: 'Key Quranic Verses on Tawheed', ms: 'Ayat-ayat Utama al-Quran tentang Tauhid', tur: 'Tevhide Dair Önemli Kuran Ayetleri', urd: 'توحید پر قرآنی آیات', ben: 'তাওহীদ সম্পর্কে গুরুত্বপূর্ণ কুরআনী আয়াত', fas: 'آیات کلیدی قرآن درباره توحید', zh: '关于认主独一的关键《古兰经》节', yue: '關於認主獨一的關鍵《古蘭經》節', ja: 'タウヒードに関する重要なクルアーンの節', ru: 'Ключевые аяты Корана о Таухиде', es: 'Versículos Coránicos Clave sobre el Tawheed', ko: '타위드에 관한 핵심 쿠란 구절' },
  section_shirk: { en: 'Shirk: Associating Partners with Allah', ms: 'Syirik: Menyekutukan Allah', tur: 'Şirk: Allah\'a Ortak Koşmak', urd: 'شرک: اللہ کے ساتھ شریک ٹھہرانا', ben: 'শিরক: আল্লাহর সাথে অংশীদার স্থাপন', fas: 'شرک: شریک قراردادن برای خدا', zh: '多神教：将伴侣与真主相联系', yue: '多神教：將伴侶與真主相聯繫', ja: 'シルク：アッラーに対する多神崇拝', ru: 'Ширк: приобщение сотоварищей к Аллаху', es: 'Shirk: Asociar Compañeros con Allah', ko: '시르크: 알라와 동반자를 결부시키는 것' },
  section_foundation: { en: 'Why Tawheed is the Foundation', ms: 'Mengapa Tauhid adalah Asas', tur: 'Tevhid Neden Temeldir', urd: 'توحید بنیاد کیوں ہے', ben: 'তাওহীদ কেন ভিত্তি', fas: 'چرا توحید اساس است', zh: '为何认主独一是基础', yue: '為何認主獨一係基礎', ja: 'なぜタウヒードが基盤なのか', ru: 'Почему Таухид является основой', es: 'Por Qué el Tawheed es la Base', ko: '타위드가 기초인 이유' },

  label_transliteration: { en: 'Transliteration', ms: 'Transliterasi', tur: 'Okunuş', urd: 'تلفظ', ben: 'উচ্চারণ', fas: 'نویسه‌گردانی', zh: '转写', yue: '轉寫', ja: '音写', ru: 'Транслитерация', es: 'Transliteración', ko: '로마자 표기' },
  label_meaning: { en: 'Meaning', ms: 'Makna', tur: 'Anlam', urd: 'معنی', ben: 'অর্থ', fas: 'معنا', zh: '含义', yue: '含義', ja: '意味', ru: 'Значение', es: 'Significado', ko: '의미' },
  label_conditions_intro: { en: 'The scholars identified seven conditions for the shahada to be valid. Merely pronouncing the words without meeting these conditions does not make one a true believer:', ms: 'Para ulama mengenal pasti tujuh syarat untuk syahadah yang sah. Sekadar mengucapkan perkataan tanpa memenuhi syarat-syarat ini tidak menjadikan seseorang mukmin sejati:', tur: 'Ulema şehadetin geçerli olması için yedi şart belirlemiştir. Sadece sözleri telaffuz etmek, bu şartları yerine getirmeden kişiyi gerçek bir mümin yapmaz:', urd: 'علماء نے شہادت کی صحت کے لیے سات شرائط متعین کی ہیں۔ محض ان شرائط کو پورا کیے بغیر الفاظ ادا کرنا انسان کو سچا مومن نہیں بناتا:', ben: 'আলেমরা শাহাদার বৈধতার জন্য সাতটি শর্ত চিহ্নিত করেছেন। এই শর্তগুলো পূরণ না করে কেবল শব্দ উচ্চারণ করা মানুষকে সত্যিকারের মুমিন বানায় না:', fas: 'علما هفت شرط برای اعتبار شهادت مشخص کرده‌اند. صرف ادای الفاظ بدون برآوردن این شرایط، انسان را مؤمن واقعی نمی‌کند:', zh: '学者们为清真言的有效性确定了七个条件。仅仅发音这些词语而不满足这些条件并不能使人成为真正的信徒：', yue: '學者們為清真言嘅有效性確定了七個條件。僅僅發音這些詞語而不滿足這些條件並唔能使人成為真正的信徒：', ja: '学者たちはシャハーダが有効であるための7つの条件を特定しました。これらの条件を満たさずに言葉を発するだけでは、真の信者にはなれません：', ru: 'Учёные выделили семь условий для действительности шахады. Простое произнесение слов без выполнения этих условий не делает человека истинным верующим:', es: 'Los eruditos identificaron siete condiciones para que la shahada sea válida. Simplemente pronunciar las palabras sin cumplir estas condiciones no convierte a alguien en un verdadero creyente:', ko: '학자들은 샤하다가 유효하기 위한 일곱 가지 조건을 확인했습니다. 이러한 조건을 충족하지 않고 단순히 말을 발음하는 것만으로는 진정한 신자가 될 수 없습니다:' },

  cat_1_name: { en: 'Tawheed al-Rububiyyah', ms: 'Tauhid al-Rububiyyah', tur: 'Tevhidu\'r-Rububiyye', urd: 'توحید الربوبیہ', ben: 'তাওহীদ আর-রুবুবিয়্যাহ', fas: 'توحید ربوبیت', zh: '主权独一（认主独一）', yue: '主權獨一', ja: 'タウヒード・ルブービーヤ', ru: 'Таухид ар-Рубубийя', es: 'Tawheed al-Rububiyyah', ko: '타위드 알루부비야' },
  cat_1_subtitle: { en: 'Oneness of Lordship', ms: 'Keesaan Ketuhanan', tur: 'Rablığın Birliği', urd: 'ربوبیت کی وحدانیت', ben: 'প্রভুত্বের একত্ব', fas: 'یگانگی در ربوبیت', zh: '主宰的独一', yue: '主宰嘅獨一', ja: '主の唯一性', ru: 'Единство Господства', es: 'Unicidad de la Señoría', ko: '주권의 유일성' },
  cat_2_name: { en: 'Tawheed al-Uluhiyyah', ms: 'Tauhid al-Uluhiyyah', tur: 'Tevhidu\'l-Uluhiyye', urd: 'توحید الالوہیہ', ben: 'তাওহীদ আল-উলুহিয়্যাহ', fas: 'توحید الوهیت', zh: '神性独一', yue: '神性獨一', ja: 'タウヒード・ウルーヒーヤ', ru: 'Таухид аль-Улюхийя', es: 'Tawheed al-Uluhiyyah', ko: '타위드 알울루히야' },
  cat_2_subtitle: { en: 'Oneness of Worship', ms: 'Keesaan Ibadah', tur: 'İbadetin Birliği', urd: 'عبادت کی وحدانیت', ben: 'ইবাদতের একত্ব', fas: 'یگانگی در عبادت', zh: '崇拜的独一', yue: '崇拜嘅獨一', ja: '礼拝の唯一性', ru: 'Единство Поклонения', es: 'Unicidad de la Adoración', ko: '예배의 유일성' },
  cat_3_name: { en: "Tawheed al-Asma' wa al-Sifat", ms: "Tauhid al-Asma' wa al-Sifat", tur: "Tevhidu'l-Esma ve's-Sıfat", urd: 'توحید الاسماء والصفات', ben: "তাওহীদ আল-আসমা' ওয়া আস-সিফাত", fas: 'توحید اسما و صفات', zh: '名称与属性的独一', yue: '名稱與屬性嘅獨一', ja: "タウヒード・アスマー・ワ・スィファート", ru: "Таухид аль-Асма' ва ас-Сифат", es: "Tawheed al-Asma' wa al-Sifat", ko: '타위드 알아스마 와 알시파트' },
  cat_3_subtitle: { en: 'Oneness of Names and Attributes', ms: 'Keesaan Nama dan Sifat', tur: 'İsim ve Sıfatların Birliği', urd: 'اسما و صفات کی وحدانیت', ben: 'নাম ও গুণাবলীর একত্ব', fas: 'یگانگی در اسما و صفات', zh: '名称与属性的独一', yue: '名稱與屬性嘅獨一', ja: '名前と属性の唯一性', ru: 'Единство Имён и Атрибутов', es: 'Unicidad de los Nombres y Atributos', ko: '이름과 속성의 유일성' },

  cond_1_name: { en: "Knowledge (al-'Ilm)", ms: 'Ilmu (al-Ilm)', tur: "İlim (el-İlm)", urd: 'علم', ben: 'জ্ঞান (আল-ইলম)', fas: 'دانش (العلم)', zh: '知识（知晓）', yue: '知識（知曉）', ja: '知識（アル・イルム）', ru: 'Знание (аль-Ильм)', es: "Conocimiento (al-'Ilm)", ko: '지식 (알일름)' },
  cond_2_name: { en: 'Certainty (al-Yaqin)', ms: 'Keyakinan (al-Yaqin)', tur: 'Yakin (el-Yakîn)', urd: 'یقین', ben: 'দৃঢ় বিশ্বাস (আল-ইয়াকিন)', fas: 'یقین (الیقین)', zh: '确信（信心坚定）', yue: '確信（信心堅定）', ja: '確信（アル・ヤキーン）', ru: 'Убеждённость (аль-Якин)', es: 'Certeza (al-Yaqin)', ko: '확신 (알야킨)' },
  cond_3_name: { en: 'Sincerity (al-Ikhlas)', ms: 'Ikhlas (al-Ikhlas)', tur: 'İhlas (el-İhlâs)', urd: 'اخلاص', ben: 'আন্তরিকতা (আল-ইখলাস)', fas: 'اخلاص', zh: '诚实（纯洁的意图）', yue: '誠實（純潔的意圖）', ja: '誠実さ（アル・イフラース）', ru: 'Искренность (аль-Ихляс)', es: 'Sinceridad (al-Ikhlas)', ko: '성실함 (알이클라스)' },
  cond_4_name: { en: 'Truthfulness (al-Sidq)', ms: 'Kejujuran (al-Sidq)', tur: 'Sıdk (es-Sıdk)', urd: 'صدق', ben: 'সত্যবাদিতা (আস-সিদক)', fas: 'صدق', zh: '真诚（真实）', yue: '真誠（真實）', ja: '誠実（アス・スィドク）', ru: 'Правдивость (ас-Сидк)', es: 'Veracidad (al-Sidq)', ko: '진실성 (알시드크)' },
  cond_5_name: { en: 'Love (al-Mahabbah)', ms: 'Kecintaan (al-Mahabbah)', tur: 'Muhabbet (el-Muhabbe)', urd: 'محبت', ben: 'ভালোবাসা (আল-মাহাব্বাহ)', fas: 'محبت (المحبة)', zh: '爱（爱戴）', yue: '愛（愛戴）', ja: '愛（アル・マハッバ）', ru: 'Любовь (аль-Махабба)', es: 'Amor (al-Mahabbah)', ko: '사랑 (알마하바)' },
  cond_6_name: { en: 'Submission (al-Inqiyad)', ms: 'Ketundukan (al-Inqiyad)', tur: 'İnkiyad (el-İnkıyad)', urd: 'انقیاد', ben: 'আনুগত্য (আল-ইনকিয়াদ)', fas: 'انقیاد', zh: '顺从（服从）', yue: '順從（服從）', ja: '服従（アル・インキヤード）', ru: 'Покорность (аль-Инкияд)', es: 'Sumisión (al-Inqiyad)', ko: '복종 (알인키야드)' },
  cond_7_name: { en: 'Acceptance (al-Qabul)', ms: 'Penerimaan (al-Qabul)', tur: 'Kabul (el-Kabûl)', urd: 'قبول', ben: 'স্বীকৃতি (আল-কাবুল)', fas: 'قبول', zh: '接受（接纳）', yue: '接受（接納）', ja: '受容（アル・カブール）', ru: 'Принятие (аль-Кабуль)', es: 'Aceptación (al-Qabul)', ko: '수용 (알카불)' },

  shirk_major_title: { en: 'Major Shirk (al-Shirk al-Akbar)', ms: 'Syirik Besar (al-Shirk al-Akbar)', tur: 'Büyük Şirk (el-Şirkü\'l-Ekber)', urd: 'شرک اکبر', ben: 'বড় শিরক (আল-শিরক আল-আকবার)', fas: 'شرک اکبر', zh: '大多神教（大伴侣）', yue: '大多神教（大伴侶）', ja: '大シルク（アル・シルク・アル・アクバル）', ru: 'Большой Ширк (аш-Ширк аль-Акбар)', es: 'Shirk Mayor (al-Shirk al-Akbar)', ko: '대시르크 (알시르크 알아크바르)' },
  shirk_minor_title: { en: 'Minor Shirk (al-Shirk al-Asghar)', ms: 'Syirik Kecil (al-Shirk al-Asghar)', tur: 'Küçük Şirk (el-Şirkü\'l-Asgar)', urd: 'شرک اصغر', ben: 'ছোট শিরক (আল-শিরক আল-আসগার)', fas: 'شرک اصغر', zh: '小多神教（小伴侣）', yue: '小多神教（小伴侶）', ja: '小シルク（アル・シルク・アル・アスガル）', ru: 'Малый Ширк (аш-Ширк аль-Асгар)', es: 'Shirk Menor (al-Shirk al-Asghar)', ko: '소시르크 (알시르크 알아스가르)' },

  foundation_1_title: { en: 'The First Question in the Grave', ms: 'Soalan Pertama di Dalam Kubur', tur: 'Kabirdeki İlk Soru', urd: 'قبر میں پہلا سوال', ben: 'কবরে প্রথম প্রশ্ন', fas: 'نخستین پرسش در قبر', zh: '坟墓中的第一个问题', yue: '墳墓中嘅第一個問題', ja: '墓の中での最初の質問', ru: 'Первый вопрос в могиле', es: 'La Primera Pregunta en la Tumba', ko: '무덤에서의 첫 번째 질문' },
  foundation_2_title: { en: 'The Decisive Matter on the Day of Judgement', ms: 'Perkara Penentu pada Hari Kiamat', tur: 'Kıyamet Günü\'ndeki Belirleyici Mesele', urd: 'قیامت کے دن فیصلہ کن معاملہ', ben: 'কিয়ামতের দিন চূড়ান্ত বিষয়', fas: 'مسئله سرنوشت‌ساز روز قیامت', zh: '末日审判的决定性事项', yue: '末日審判嘅決定性事項', ja: '審判の日の決定的な事柄', ru: 'Решающий вопрос Судного дня', es: 'El Asunto Decisivo en el Día del Juicio', ko: '심판의 날의 결정적인 사항' },
  foundation_3_title: { en: 'The Mission of Every Prophet', ms: 'Misi Setiap Nabi', tur: 'Her Peygamberin Misyonu', urd: 'ہر نبی کی بعثت', ben: 'প্রতিটি নবীর মিশন', fas: 'رسالت هر پیامبر', zh: '每位先知的使命', yue: '每位先知嘅使命', ja: 'すべての預言者の使命', ru: 'Миссия каждого пророка', es: 'La Misión de Cada Profeta', ko: '모든 예언자의 사명' },
  foundation_4_title: { en: 'La ilaha illallah: The Greatest Statement', ms: 'La ilaha illallah: Pernyataan Terbesar', tur: "La ilahe illallah: En Büyük Söz", urd: 'لا الہ الا اللہ: سب سے عظیم کلمہ', ben: 'লা ইলাহা ইল্লাল্লাহ: সর্বশ্রেষ্ঠ বাণী', fas: 'لا اله الا الله: بزرگ‌ترین گفته', zh: '"万物非主，唯有真主"：最伟大的宣言', yue: '"萬物非主，唯有真主"：最偉大的宣言', ja: '"ラー・イラーハ・イッラッラー"：最も偉大な言葉', ru: '"Ля иляха илляллах": Величайшее высказывание', es: 'La ilaha illallah: La Mayor Declaración', ko: '"라 일라하 일랄라": 가장 위대한 선언' },

  closing_verse: { en: '"So know that there is no deity except Allah." (Quran 47:19)', ms: '"Maka ketahuilah bahawa tiada Tuhan yang berhak disembah selain Allah." (Quran 47:19)', tur: '"Bil ki Allah\'tan başka ilah yoktur." (Kuran 47:19)', urd: '"پس جان لو کہ اللہ کے سوا کوئی معبود نہیں۔" (القرآن ۴۷:۱۹)', ben: '"সুতরাং জেনে রাখো যে আল্লাহ ছাড়া কোনো উপাস্য নেই।" (কুরআন ৪৭:১৯)', fas: '"پس بدان که هیچ معبودی جز الله نیست." (قرآن ۴۷:۱۹)', zh: '"因此要知道，除真主外别无神明。"（古兰经47:19）', yue: '"因此要知道，除真主外別無神明。"（古蘭經47:19）', ja: '"それゆえ、アッラー以外に神はないことを知れ。"（クルアーン47:19）', ru: '"Знай же, что нет божества, кроме Аллаха." (Коран 47:19)', es: '"Por tanto, sabe que no hay más deidad que Allah." (Quran 47:19)', ko: '"따라서 알라 외에 신이 없음을 알라." (쿠란 47:19)' },
  closing_note: { en: 'This verse commands knowledge of Tawheed before deeds: it is the foundation upon which everything else is built.', ms: 'Ayat ini memerintahkan pengetahuan tentang Tauhid sebelum amalan: ia adalah asas di mana segala sesuatu yang lain dibina.', tur: 'Bu ayet, amelden önce Tevhid bilgisini emreder: üzerine her şeyin inşa edildiği temeldir.', urd: 'یہ آیت اعمال سے پہلے توحید کا علم حاصل کرنے کا حکم دیتی ہے: یہ وہ بنیاد ہے جس پر باقی سب کچھ قائم ہے۔', ben: 'এই আয়াত কর্মের আগে তাওহীদের জ্ঞান অর্জনের নির্দেশ দেয়: এটি সেই ভিত্তি যার উপর অন্য সবকিছু নির্মিত।', fas: 'این آیه پیش از اعمال، دانستن توحید را واجب می‌داند: این اساسی است که هر چیز دیگری بر آن بنا شده است.', zh: '这节经文要求在行善之前认识认主独一：它是一切其他事物建立的基础。', yue: '這節經文要求在行善之前認識認主獨一：它係一切其他事物建立嘅基礎。', ja: 'この節は行いの前にタウヒードの知識を命じています：それは他のすべてが築かれる基盤です。', ru: 'Этот аят повелевает знание Таухида прежде дел: это основа, на которой строится всё остальное.', es: 'Este versículo ordena el conocimiento del Tawheed antes que las obras: es el fundamento sobre el que se construye todo lo demás.', ko: '이 구절은 행위 이전에 타위드의 지식을 명령합니다: 이것이 다른 모든 것이 세워지는 기초입니다.' },
} satisfies Record<string, LangMap>;
