import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic();

const LANGUAGE_NAMES: Record<string, string> = {
  'en': 'English (British)',
  'ar': 'Arabic',
  'es': 'Spanish',
  'ms': 'Malay (Bahasa Malaysia)',
  'zh-cmn': 'Mandarin Chinese (Simplified)',
  'zh-yue': 'Cantonese (Traditional Chinese characters)',
  'ja': 'Japanese',
};

function buildSystemPrompt(language: string, type: 'translation' | 'context'): string {
  const langName = LANGUAGE_NAMES[language] ?? language;

  if (type === 'context') {
    return `You are a scholar of Islamic hadith sciences writing in ${langName}.
Your task is to explain the background, reason, and context of a hadith (known as asbab al-wurud in Arabic scholarship).

Write clearly and accessibly for both Muslims and non-Muslims. Cover:
- Who said this hadith and to whom
- The circumstances or occasion that prompted this statement
- What situation it was addressing
- Key scholarly commentary on its meaning and application
- Why this particular hadith is significant

Use formal, respectful language. Do not use the phrase "Generated by AI" or mention AI.
Write in ${langName} throughout, except for Arabic terms which may be transliterated.
Keep your response between 200–400 words.
Use British English spelling and conventions if writing in English.`;
  }

  return `You are a scholarly translator specialising in Islamic texts. Translate the following hadith text into ${langName}.

CRITICAL GUIDELINES:
- Produce a CONTEXTUAL, IDIOMATIC translation — not a word-for-word literal one
- The meaning must be natural and clear to a native speaker of ${langName}
- For Japanese: use appropriate keigo (polite/formal register), honour the cultural sensitivity of religious text, and ensure the sentence structure flows naturally in Japanese — do not force Arabic grammatical structure into Japanese
- For Cantonese: use Traditional Chinese characters appropriate to Cantonese, with natural Cantonese phrasing rather than Mandarin-influenced constructions
- For Mandarin: use Simplified Chinese characters with clear, contemporary literary prose
- For Arabic: provide a classical Arabic rendering that respects the original prophetic style
- Preserve the dignity and reverence appropriate for prophetic speech
- Keep any technical Islamic terms (e.g. salah, zakat) — you may transliterate them and add a brief parenthetical explanation
- Do NOT add your own commentary, footnotes, or meta-text — provide only the translation itself
- Do NOT mention that you are an AI or that this is a translation

Respond with ONLY the translated text, nothing else.`;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { text, arabic, language, type, collection, hadithNumber } = body;

    if (!text || !language || !type) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    if (language === 'en' && type === 'translation') {
      return NextResponse.json({ result: text });
    }

    const systemPrompt = buildSystemPrompt(language, type);

    let userMessage: string;
    if (type === 'context') {
      userMessage = `This is hadith number ${hadithNumber} from ${collection ?? 'a canonical hadith collection'}.

Arabic text: ${arabic ?? '(not available)'}

English meaning: ${text}

Please explain the background, context, and reason behind this hadith in ${LANGUAGE_NAMES[language] ?? language}.`;
    } else {
      userMessage = `Translate this hadith text into ${LANGUAGE_NAMES[language] ?? language}:\n\n${text}`;
    }

    const response = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      system: systemPrompt,
      messages: [{ role: 'user', content: userMessage }],
    });

    const result =
      response.content[0].type === 'text' ? response.content[0].text : '';

    return NextResponse.json({ result });
  } catch (err) {
    console.error('Translation error:', err);
    return NextResponse.json({ error: 'Translation service unavailable' }, { status: 500 });
  }
}
