'use client';

import { PageHeader } from '@/components/ui/PageHeader';
import { UnderConstructionCallout } from '@/components/ui/UnderConstructionCallout';
import { useLanguage } from '@/lib/i18n/context';

const TITLE: Record<string, string> = {
  en: `Prohibited Materials and Colours in Clothing`,
  ms: `Bahan dan Warna Pakaian yang Dilarang`,
  tur: `Giyimde Yasaklanan Kumaş ve Renkler`,
  urd: `لباس میں ممنوعہ مواد اور رنگ`,
  ben: `পোশাকে নিষিদ্ধ উপাদান ও রঙ`,
  fas: `مواد و رنگ‌های ممنوع در لباس`,
  zh: `服饰中禁用之材质与颜色`,
  yue: `服飾中禁用之材質同顏色`,
  ja: `衣服における禁じられた素材と色`,
  ru: `Запретные материалы и цвета в одежде`,
  es: `Materiales y colores prohibidos en el vestir`,
  ko: `의복에서 금지된 재질과 색`,
  ta: `ஆடையில் தடைசெய்யப்பட்ட பொருட்கள் மற்றும் வண்ணங்கள்`,
  si: `ඇඳුමේ තහනම් ද්‍රව්‍ය සහ වර්ණ`,
};

const SUBTITLE: Record<string, string> = {
  en: `Silk for men, gold jewellery for men, garments of pride, imitation of the opposite gender, and the pure red garment  –  the specific hadith prohibitions and the wisdom behind each.`,
  ms: `Sutera bagi lelaki, barangan emas bagi lelaki, pakaian kesombongan, meniru jantina yang bertentangan, dan pakaian merah tulen  –  larangan hadis yang khusus dan hikmah di sebalik setiap satu.`,
  tur: `Erkeğe ipek, erkeğe altın takı, kibir elbiseleri, karşı cinse benzeme ve safi kırmızı giysi  –  hususi hadis yasakları ve her birinin ardındaki hikmet.`,
  urd: `مرد کے لیے ریشم، مرد کے لیے سونے کے زیورات، تکبر کے کپڑے، مخالف جنس کی نقل، اور خالص سرخ لباس  –  مخصوص حدیثی ممانعت اور ہر ایک کے پیچھے حکمت۔`,
  ben: `পুরুষের জন্য রেশম, পুরুষের জন্য স্বর্ণালঙ্কার, অহংকারের পোশাক, বিপরীত লিঙ্গের অনুকরণ, এবং খাঁটি লাল পোশাক  –  নির্দিষ্ট হাদিসের নিষেধাজ্ঞা এবং প্রত্যেকটির পিছনের হিকমাহ।`,
  fas: `ابریشم برای مردان، طلا برای مردان، جامه‌ی تکبر، شبیه‌سازی به جنس مخالف، و جامه‌ی سرخ خالص  –  نهی‌های خاص حدیث و حکمت پشت هر یک.`,
  zh: `男子丝绸、男子金饰、骄矜之衣、模仿异性、纯红衣裳  –  具体之圣训禁令及各之背后智慧。`,
  yue: `男子絲綢、男子金飾、驕矜之衣、模仿異性、純紅衣裳  –  具體之聖訓禁令及各之背後智慧。`,
  ja: `男性の絹、男性の金の装身具、傲慢の衣、異性の模倣、純赤の衣  –  それぞれのハディースによる禁止と、その背後にある叡智。`,
  ru: `Шёлк для мужчин, золото для мужчин, одежды гордыни, подражание противоположному полу и чисто-красная одежда  –  конкретные хадисные запреты и мудрость каждого.`,
  es: `Seda para el varón, joyas de oro para el varón, prendas de soberbia, imitación del sexo opuesto y la prenda de rojo puro  –  las prohibiciones específicas de los hadices y la sabiduría de cada una.`,
  ko: `남성의 비단, 남성의 금 장신구, 오만의 옷, 이성 모방, 순수 붉은 옷  –  구체적인 하디스 금지와 그 배후의 지혜.`,
  ta: `ஆண்களுக்கு பட்டு, ஆண்களுக்கு தங்க நகைகள், ஆடம்பரமான ஆடைகள், எதிர் பாலினத்தைப் போலியாய் அமைத்தல், மற்றும் தூய சிவப்பு ஆடை  –  குறிப்பிட்ட ஹதீஸ் தடைகள் மற்றும் ஒவ்வொன்றின் பின்னாலுள்ள ஞானம்.`,
  si: `පිරිමින්ට සිල්ක්, පිරිමින්ට රන් ආභරණ, ආඩම්බර ඇඳුම්, විරුද්ධ ලිංගිකත්වයට අනුකරණය, සහ පිරිසිදු රතු ඇඳුම  –  නිශ්චිත හදීස් තහනම් සහ ඒ එක් එක් පිටුපස ඇති ප්‍රඥාව.`,
};

const TOPIC: Record<string, string> = {
  en: `Coming: the Prophet's ﷺ two-fold hadith holding silk and gold in one hand, then saying "These two are haram for the males of my nation, halal for its females" (Abu Dawud 4057, Nasa'i 5144); the ruling on silk-blend and small silk trim (permitted per some, limited by hadith); gold jewellery of any kind haram for men (rings, chains  –  Muslim 2078), but silver is permitted (the Prophet ﷺ wore a silver ring  –  Bukhari 5866); the fierce condemnation of isbal  –  letting the garment drag below the ankle out of pride (three men Allah will not speak to on Judgement Day  –  Muslim 106); the prohibition of the pure red garment for men in some narrations (Abu Dawud 4067, though scholars differ) versus the general permission of red and orange dyed fabrics (Bukhari 5811); the prohibition of imitating the opposite gender in dress (Bukhari 5885, cursing men who imitate women and vice versa); the prohibition of imitating the disbelievers in specifically religious dress; and the reason behind each of these  –  humility, distinction from paganism, gender-role clarity, avoidance of ostentation, and preservation of male masculinity and female modesty.`,
  ms: `Akan datang: hadis Nabi ﷺ mengangkat sutera dan emas dalam satu tangan lalu bersabda "Kedua-dua ini haram untuk lelaki umatku, halal untuk perempuannya" (Abu Dawud 4057, Nasa'i 5144); hukum campuran sutera dan sedikit hiasan sutera (dibenarkan menurut sebahagian, terhad oleh hadis); barangan emas jenis apa pun haram bagi lelaki (cincin, rantai  –  Muslim 2078), tetapi perak dibenarkan (Nabi ﷺ memakai cincin perak  –  Bukhari 5866); kecaman keras terhadap isbal  –  menjulur pakaian di bawah buku lali kerana sombong (tiga lelaki yang Allah tidak akan bercakap dengan mereka pada Hari Kiamat  –  Muslim 106); larangan pakaian merah tulen untuk lelaki dalam beberapa riwayat (Abu Dawud 4067, walaupun ulama berbeza pendapat) berbanding izin umum bagi kain berwarna merah dan oren (Bukhari 5811); larangan meniru jantina lawan dalam pakaian (Bukhari 5885, laknat kepada lelaki yang meniru perempuan dan sebaliknya); larangan meniru orang bukan Islam dalam pakaian keagamaan khusus; dan sebab di sebalik setiap satu  –  kerendahan hati, pembezaan daripada paganisme, kejelasan peranan jantina, mengelakkan pameran, dan pemeliharaan kejantanan lelaki dan kesopanan wanita.`,
  tur: `Yakında: Hz. Peygamber'in ﷺ ipek ve altını bir elde tutup "Bu ikisi ümmetimin erkeklerine haram, kadınlarına helâldir" buyurduğu hadis (Ebû Dâvud 4057, Nesâî 5144); ipek karışımlı kumaş ve az miktarda ipek şeridin hükmü (bir kısmına göre câiz, hadîs ile sınırlı); her türlü altın takının erkeğe haramlığı (yüzük, zincir  –  Müslim 2078), gümüşün ise cevâzı (Hz. Peygamber ﷺ gümüş yüzük takmıştır  –  Buhârî 5866); kibirle eteği topuklardan aşağı sarkıtmaya karşı şiddetli kınama (Kıyamet Günü Allah'ın kendileriyle konuşmayacağı üç kişiden biri  –  Müslim 106); bazı rivayetlerde erkek için safi kırmızı elbisenin yasağı (Ebû Dâvud 4067, âlimler ihtilâflıdır) ile kırmızı ve turuncuya boyanmış kumaşların umum cevâzı (Buhârî 5811) arasındaki nüans; kılıkta karşı cinse benzemenin yasaklanışı (Buhârî 5885, kadına benzeyen erkeğe ve erkeğe benzeyen kadına lânet); kâfirlere özellikle dini kılık kıyafette benzemenin yasaklanışı; ve her birinin ardındaki sebep  –  tevazu, putperestlikten ayrışma, cinsiyet rollerinin netliği, gösterişten kaçınma ve erkeklik ile kadın haya-tesettürünün korunması.`,
  urd: `آنے والا: نبی ﷺ نے ایک ہاتھ میں ریشم اور سونا اٹھا کر فرمایا "یہ دونوں میری امت کے مردوں پر حرام اور عورتوں پر حلال ہیں" (ابو داود ۴۰۵۷، نسائی ۵۱۴۴)؛ ریشمی آمیزش اور معمولی ریشمی حاشیے کا حکم (بعض کے مطابق جائز، حدیث سے محدود)؛ ہر قسم کے سونے کے زیورات مردوں کے لیے حرام (انگوٹھی، زنجیر  –  مسلم ۲۰۷۸)، مگر چاندی جائز (نبی ﷺ نے چاندی کی انگوٹھی پہنی  –  بخاری ۵۸۶۶)؛ اسبال کی سخت مذمت  –  تکبر سے کپڑا ٹخنوں سے نیچے گھسیٹنا (تین آدمی جن سے اللہ قیامت کے دن بات نہ کرے گا  –  مسلم ۱۰۶)؛ مردوں کے لیے خالص سرخ لباس کی ممانعت بعض روایات میں (ابو داود ۴۰۶۷، اگرچہ علماء کا اختلاف)، جبکہ سرخ اور نارنجی رنگے کپڑوں کی عمومی اجازت (بخاری ۵۸۱۱)؛ لباس میں مخالف جنس کی نقل کی ممانعت (بخاری ۵۸۸۵، عورتوں کی نقل کرنے والے مردوں اور برعکس پر لعنت)؛ خصوصاً دینی لباس میں کافروں کی نقل کی ممانعت؛ اور ہر ایک کے پیچھے سبب  –  عاجزی، شرک سے تمیز، جنسی کردار کی وضاحت، دکھاوے سے بچنا، اور مردانگی و نسوانی حیا کا تحفظ۔`,
  ben: `আসছে: নবী ﷺ এক হাতে সিল্ক ও স্বর্ণ ধরে বলেছেন "এই দুটি আমার উম্মতের পুরুষদের জন্য হারাম, নারীদের জন্য হালাল" (আবু দাউদ ৪০৫৭, নাসাঈ ৫১৪৪); সিল্ক-মিশ্রণ ও সামান্য সিল্ক কিনারার বিধান (কিছুর মতে অনুমোদিত, হাদিস অনুযায়ী সীমিত); যেকোনো ধরনের স্বর্ণালঙ্কার পুরুষদের জন্য হারাম (আংটি, চেইন  –  মুসলিম ২০৭৮), কিন্তু রূপা অনুমোদিত (নবী ﷺ রূপার আংটি পরেছেন  –  বুখারি ৫৮৬৬); ইসবালের কঠোর নিন্দা  –  অহংকারে গোড়ালির নিচে পোশাক টেনে রাখা (কিয়ামতের দিন যেসব তিনজনের সাথে আল্লাহ কথা বলবেন না  –  মুসলিম ১০৬); কিছু বর্ণনায় পুরুষদের জন্য খাঁটি লাল পোশাকের নিষেধ (আবু দাউদ ৪০৬৭, যদিও আলিমদের মধ্যে মতভেদ) বনাম লাল ও কমলা রঙের কাপড়ের সাধারণ অনুমতি (বুখারি ৫৮১১); পোশাকে বিপরীত লিঙ্গের অনুকরণের নিষেধ (বুখারি ৫৮৮৫, নারীদের অনুকরণকারী পুরুষ ও উল্টো লানত); বিশেষত ধর্মীয় পোশাকে অমুসলিমদের অনুকরণের নিষেধ; এবং প্রত্যেকটির পিছনের কারণ  –  বিনয়, পৌত্তলিকতা থেকে পার্থক্য, লিঙ্গ ভূমিকার স্পষ্টতা, লোক দেখানো থেকে বিরত থাকা, এবং পুরুষত্ব ও নারীর শালীনতার সংরক্ষণ।`,
  fas: `به‌زودی: حدیث پیامبر ﷺ که ابریشم و طلا را در یک دست گرفت و فرمود «این دو بر مردان امتم حرام و بر زنانش حلال است» (ابوداود ۴۰۵۷، نسائی ۵۱۴۴)؛ حکم پارچه‌ی ابریشمی مخلوط و حاشیه‌ی ابریشمی اندک (به عقیده‌ی برخی جایز، محدود به حدیث)؛ هر گونه زیور طلا برای مردان حرام (انگشتر، زنجیر  –  مسلم ۲۰۷۸)، اما نقره جایز است (پیامبر ﷺ انگشتر نقره داشتند  –  بخاری ۵۸۶۶)؛ نکوهش شدید اسبال  –  کشیدن لباس از سر تکبر تا زیر قوزک (سه کس که خدا در قیامت با آنان سخن نمی‌گوید  –  مسلم ۱۰۶)؛ نهی از پوشیدن جامه‌ی سرخ خالص برای مردان در برخی روایات (ابوداود ۴۰۶۷، هرچند علما اختلاف دارند) در مقابل جواز عمومی پارچه‌های سرخ و نارنجی رنگ‌شده (بخاری ۵۸۱۱)؛ نهی از شبیه‌سازی به جنس مخالف در پوشش (بخاری ۵۸۸۵، لعن مردان مانند زنان و بالعکس)؛ نهی از شبیه‌سازی به کافران در پوشش خاص دینی؛ و سبب هر یک  –  فروتنی، تمایز از شرک، شفافیت نقش‌های جنسیتی، پرهیز از خودنمایی، و حفظ مردانگی مردان و عفاف زنان.`,
  zh: `即将推出：先知 ﷺ 一手同持丝绸与金，云「此二者，我教之男者哈拉姆，女者哈拉勒」（艾布·达乌德 4057，奈萨仪 5144）；混纺与少量丝边之判决（部分认为可，依圣训受限）；一切金饰对男子皆禁（戒指、项链  –  穆斯林 2078），而银则许可（先知 ﷺ 曾戴银戒  –  布哈里 5866）；对「伊斯巴勒」（骄矜曳衣过踝）之严厉谴责（复生日安拉不与之言的三人之一  –  穆斯林 106）；某些传述中禁男子着纯红衣（艾布·达乌德 4067，然学者意见有别）与红橙染物之一般允许（布哈里 5811）之别；服饰上禁效异性（布哈里 5885，效女之男与效男之女皆蒙诅咒）；尤其宗教服饰上禁效非穆斯林；及各项背后之原因  –  谦卑、与偶像崇拜有别、性别角色清晰、避免炫耀、以及男子之阳刚与女子之端庄之维护。`,
  yue: `即將推出：先知 ﷺ 一手同持絲綢與金，云「此二者，我教之男者哈拉姆，女者哈拉勒」（艾布·達烏德 4057，奈薩儀 5144）；混紡同少量絲邊之判決（部分認為可，依聖訓受限）；一切金飾對男子皆禁（戒指、項鏈  –  穆斯林 2078），而銀則許可（先知 ﷺ 曾戴銀戒  –  布哈里 5866）；對「伊斯巴勒」（驕矜曳衣過踝）之嚴厲譴責（復生日安拉不與之言嘅三人之一  –  穆斯林 106）；某些傳述中禁男子著純紅衣（艾布·達烏德 4067，然學者意見有別）與紅橙染物之一般允許（布哈里 5811）之別；服飾上禁效異性（布哈里 5885，效女之男同效男之女皆蒙詛咒）；尤其宗教服飾上禁效非穆斯林；及各項背後之原因  –  謙卑、與偶像崇拜有別、性別角色清晰、避免炫耀、以及男子之陽剛同女子之端莊之維護。`,
  ja: `近日追加：預言者 ﷺ が絹と金を一方の手に持ち、「この二つは私の共同体の男には禁じられ、女には許される」と仰せられたハディース（アブー・ダーウード 4057、ナサーイー 5144）、絹の混紡や少量の絹の縁取りの規定（一部で許容、ハディースにより制限）、あらゆる金の装身具は男に禁（指輪、鎖  –  ムスリム 2078）、しかし銀は許される（預言者 ﷺ は銀の指輪を用いられた  –  ブハーリー 5866）、傲慢からくるイスバール（衣を踝より下に引きずる）への厳しい叱責（復活の日にアッラーが語りかけない三人の一つ  –  ムスリム 106）、一部の伝えにおける男性の純赤の衣の禁（アブー・ダーウード 4067、学者見解の相違あり）と、赤や橙に染めた布の一般的な許可（ブハーリー 5811）の対比、装いにおける異性の模倣の禁（ブハーリー 5885、女装の男・男装の女への呪詛）、特に宗教的装いにおける不信仰者の模倣の禁、そしてそれぞれの背後にある理由  –  謙虚、偶像崇拝との差別、ジェンダー役割の明瞭さ、誇示の回避、男らしさと女の慎みの保持。`,
  ru: `Скоро: хадис Пророка ﷺ, взявшего в одну руку шёлк и золото и сказавшего "Эти два запретны для мужчин моей общины, разрешены для её женщин" (Абу Дауд 4057, Насаи 5144); правило о смесовых тканях и небольшой шёлковой отделке (по некоторым разрешено, по хадису ограничено); любые золотые украшения запретны мужчинам (перстни, цепочки  –  Муслим 2078), но серебро разрешено (Пророк ﷺ носил серебряный перстень  –  аль-Бухари 5866); жёсткое осуждение исбал  –  волочения одежды ниже щиколотки из гордыни (одни из трёх, с которыми Аллах не заговорит в Судный день  –  Муслим 106); запрет чисто-красной одежды для мужчин в некоторых передачах (Абу Дауд 4067, есть расхождение), при общем разрешении красной и оранжевой окраски (аль-Бухари 5811); запрет подражания противоположному полу в одежде (аль-Бухари 5885, проклятие мужчинам, уподобляющимся женщинам, и наоборот); запрет уподобления неверующим именно в религиозной одежде; и мудрость каждого  –  смирение, отличение от язычества, ясность гендерных ролей, отказ от показного и сохранение мужественности мужчин и скромности женщин.`,
  es: `Próximamente: el hadiz del Profeta ﷺ que tomó seda y oro en una mano y dijo «Estos dos son haram para los varones de mi nación, halal para sus mujeres» (Abu Dawud 4057, Nasa'i 5144); el fallo sobre las mezclas de seda y los pequeños ribetes de seda (permitido según algunos, limitado por el hadiz); las joyas de oro de cualquier tipo son haram para el varón (anillos, cadenas  –  Muslim 2078), pero la plata está permitida (el Profeta ﷺ llevó un anillo de plata  –  al-Bukhari 5866); la condena severa del isbal  –  arrastrar la prenda por debajo del tobillo por soberbia (uno de los tres a quienes Al-lah no hablará el Día del Juicio  –  Muslim 106); la prohibición de la prenda de rojo puro para el varón en algunas narraciones (Abu Dawud 4067, aunque los sabios difieren) frente al permiso general de las telas teñidas de rojo y naranja (al-Bukhari 5811); la prohibición de imitar al sexo opuesto en el vestir (al-Bukhari 5885, maldición sobre los hombres que imitan a las mujeres y viceversa); la prohibición de imitar a los no creyentes específicamente en el vestir religioso; y la razón detrás de cada una  –  humildad, distinción del paganismo, claridad en los roles de género, evitar la ostentación y la preservación de la masculinidad del varón y el pudor de la mujer.`,
  ko: `공개 예정: 예언자 ﷺ 께서 한 손에 비단과 금을 쥐고 "이 두 가지는 내 공동체의 남자들에게 하람이며, 여자들에게 할랄이다"라고 하신 하디스(아부 다우드 4057, 나사이 5144); 비단 혼방과 소량의 비단 장식에 관한 규정(일부 견해로는 허용, 하디스에 의해 제한); 모든 종류의 금 장신구는 남성에게 하람(반지, 목걸이  –  무슬림 2078); 그러나 은은 허용됨(예언자 ﷺ 께서 은반지를 착용하심  –  알부카리 5866); 이스발  –  교만하게 옷자락을 발목 아래로 끄는 것에 대한 강한 규탄(심판의 날에 알라께서 말씀하지 않으실 세 사람 중 하나  –  무슬림 106); 일부 전승에서 남성의 순수 붉은 옷 금지(아부 다우드 4067, 학자들 견해 상이) 대 일반적으로 붉은색·주황색 염색 옷 허용(알부카리 5811); 이성 모방 금지(알부카리 5885, 여자를 흉내내는 남자와 남자를 흉내내는 여자에 대한 저주); 특히 종교적 의복에서 불신자를 모방하는 것의 금지; 그리고 각 규정의 이유  –  겸손, 우상 숭배와의 구별, 성 역할의 명확성, 과시 회피, 그리고 남자의 남성성과 여자의 정숙함의 보존.`,
  ta: `விரைவில் வரும்: நபி ﷺ ஒரு கையில் பட்டு மற்றும் தங்கத்தை பிடித்து "இவை இரண்டும் என் சமூகத்தின் ஆண்களுக்கு ஹராம், பெண்களுக்கு ஹலால்" என்று கூறிய ஹதீஸ் (அபூ தாவூத் 4057, நஸாயீ 5144); பட்டு கலப்பு மற்றும் சிறிய பட்டு விளிம்பின் விதி (சிலரின் படி அனுமதி, ஹதீஸ் மூலம் வரம்புகள்); எந்த வகையான தங்க நகைகளும் ஆண்களுக்கு ஹராம் (மோதிரம், சங்கிலி  –  முஸ்லிம் 2078), ஆனால் வெள்ளி அனுமதிக்கப்பட்டது (நபி ﷺ வெள்ளி மோதிரம் அணிந்தார்  –  புகாரி 5866); இஸ்பாலின் கடுமையான கண்டனம்  –  ஆடையை ஆடம்பரத்தால் கணுக்காலுக்குக் கீழே இழுத்தல் (இறுதி நாளில் அல்லாஹ் பேசாத மூவரில் ஒருவர்  –  முஸ்லிம் 106); சில அறிவிப்புகளில் ஆண்களுக்கு தூய சிவப்பு ஆடையின் தடை (அபூ தாவூத் 4067, அறிஞர்கள் மாறுபட்டு உள்ளனர்) மற்றும் சிவப்பு-ஆரஞ்சு நிற ஆடைகளின் பொது அனுமதி (புகாரி 5811) இடையேயான வேறுபாடு; ஆடையில் எதிர் பாலினத்தை போன்று செயல்படுவது தடை (புகாரி 5885, பெண்களைப் போன்று மாறும் ஆண்கள் மற்றும் நேர்மாறாக சபிக்கப்பட்டவர்கள்); குறிப்பாக மத ஆடையில் நம்பிக்கை கொள்ளாதவர்களை போன்று செயல்படுவது தடை; மற்றும் ஒவ்வொன்றின் பின்னாலுள்ள காரணம்  –  பணிவு, பாகனிசத்திலிருந்து வேறுபாடு, பாலின பாத்திரங்களின் தெளிவு, ஆடம்பரத்தைத் தவிர்த்தல், மற்றும் ஆண்களின் ஆண்மை மற்றும் பெண்களின் கண்ணியத்தின் பாதுகாப்பு.`,
  si: `ඉදිරියේදී: නබි ﷺ තුමා එක් අතකින් සිල්ක් සහ රත්‍රන් ගෙන "මේ දෙක මාගේ ජාතියේ පිරිමින්ට හරාම්, කාන්තාවන්ට හලාල්" යැයි වදාළ හදීසය (අබූ දාවූද් 4057, නසාඉ 5144); සිල්ක් මිශ්‍රණ සහ කුඩා සිල්ක් දාරයේ නීතිය (සමහරන්ට අනුව අනුමතයි, හදීසය මගින් සීමා කර ඇත); ඕනෑම වර්ගයක රන් ආභරණ පිරිමින්ට හරාම් (මුදු, දාම්  –  මුස්ලිම් 2078), නමුත් රිදී අනුමතයි (නබි ﷺ තුමා රිදී මුද්දක් පැළඳූහ  –  බුකාරි 5866); ඉස්බාල් සඳහා දැඩි හෙළා දැක්වීම  –  ආඩම්බරයෙන් ඇඳුම වළලුකරට පහළින් ඇදගෙන යාම (විනිශ්චය දිනයේ අල්ලාහ් කථා නොකරන පුද්ගලයන් තිදෙනාගෙන් එකෙකි  –  මුස්ලිම් 106); සමහර වාර්තාවල පිරිමින්ට පිරිසිදු රතු ඇඳුම තහනම් (අබූ දාවූද් 4067, විද්වතුන් වෙනස් වේ) සහ රතු සහ තැඹිලි පැහැති රෙදිවලට පොදු අවසරය (බුකාරි 5811) අතර වෙනස; ඇඳුමින් විරුද්ධ ලිංගිකත්වයට අනුකරණය කිරීමේ තහනම (බුකාරි 5885, කාන්තාවන් අනුකරණය කරන පිරිමින්ට සහ පිරිමින් අනුකරණය කරන කාන්තාවන්ට ශාප); විශේෂයෙන් ආගමික ඇඳුමින් අවිශ්වාසිකයන් අනුකරණය කිරීමේ තහනම; සහ එක් එක්කම පිටුපස ඇති හේතුව  –  නිහතමානිත්වය, පෞරාණික ආගම්වලින් වෙනස්කම, ලිංගික භූමිකා පැහැදිලිකම, ආඩම්බර ප්‍රදර්ශනය වළක්වා ගැනීම, සහ පිරිමින්ගේ පුරුෂ ස්වභාවය සහ කාන්තාවන්ගේ ලජ්ජාව ආරක්‍ෂා කිරීම.`,
};

export function ProhibitedClothingContent() {
  const { lang } = useLanguage();
  return (
    <>
      <PageHeader
        title={TITLE[lang] ?? TITLE.en}
        arabicTitle="المُحَرَّمَاتُ فِي اللِّبَاس"
        subtitle={SUBTITLE[lang] ?? SUBTITLE.en}
      />
      <div className="max-w-4xl mx-auto px-6 py-16">
        <UnderConstructionCallout topic={TOPIC} />
      </div>
    </>
  );
}
